// Code generated by command: go run asm.go -out lower_amd64.s -arm64 lower_arm64.s -stubs stub.go -arm64-promote-stack-slots. DO NOT EDIT.

#include "textflag.h"

// func Add(x uint64, y uint64) uint64
TEXT ·Add(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	ADDQ AX, CX
	MOVQ CX, ret+16(FP)
	RET

// func Sub(x uint64, y uint64) uint64
TEXT ·Sub(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	SUBQ CX, AX
	MOVQ AX, ret+16(FP)
	RET

// func Neg(x uint64) uint64
TEXT ·Neg(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	NEGQ AX
	MOVQ AX, ret+8(FP)
	RET

// func AndOrXor(x uint64, y uint64) uint64
TEXT ·AndOrXor(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	MOVQ AX, DX
	ANDQ CX, DX
	ORQ  CX, AX
	XORQ AX, DX
	MOVQ DX, ret+16(FP)
	RET

// func ShlCL(x uint64, n uint64) uint64
TEXT ·ShlCL(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ n+8(FP), CX
	SHLQ CL, AX
	MOVQ AX, ret+16(FP)
	RET

// func ShrCL(x uint64, n uint64) uint64
TEXT ·ShrCL(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ n+8(FP), CX
	SHRQ CL, AX
	MOVQ AX, ret+16(FP)
	RET

// func RolCL(x uint64, n uint64) uint64
TEXT ·RolCL(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ n+8(FP), CX
	ROLQ CL, AX
	MOVQ AX, ret+16(FP)
	RET

// func ZeroExt32(x uint64) uint64
TEXT ·ZeroExt32(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	MOVL AX, CX
	ADDQ AX, CX
	MOVQ CX, ret+8(FP)
	RET

// func HighByte(x uint64) uint64
TEXT ·HighByte(SB), NOSPLIT, $0-16
	MOVQ    x+0(FP), AX
	MOVB    AH, AL
	MOVBQZX AL, AX
	MOVQ    AX, ret+8(FP)
	RET

// func LoadIdx(p *[8]uint64, i uint64) uint64
TEXT ·LoadIdx(SB), NOSPLIT, $0-24
	MOVQ p+0(FP), AX
	MOVQ i+8(FP), CX
	MOVQ (AX)(CX*8), AX
	MOVQ AX, ret+16(FP)
	RET

// func Copy16(dst *[16]byte, src *[16]byte)
// Requires: SSE
TEXT ·Copy16(SB), NOSPLIT, $0-16
	MOVQ   dst+0(FP), AX
	MOVQ   src+8(FP), CX
	MOVUPS (CX), X0
	MOVUPS X0, (AX)
	RET

// func LessS(a uint64, b uint64) uint64
TEXT ·LessS(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPQ AX, CX
	JLT  LessS_yes
	MOVQ $0x0000000000000000, AX
	JMP  LessS_end

LessS_yes:
	MOVQ $0x0000000000000001, AX

LessS_end:
	MOVQ AX, ret+16(FP)
	RET

// func GreaterEqS(a uint64, b uint64) uint64
TEXT ·GreaterEqS(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPQ AX, CX
	JGE  GreaterEqS_yes
	MOVQ $0x0000000000000000, AX
	JMP  GreaterEqS_end

GreaterEqS_yes:
	MOVQ $0x0000000000000001, AX

GreaterEqS_end:
	MOVQ AX, ret+16(FP)
	RET

// func LessU(a uint64, b uint64) uint64
TEXT ·LessU(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPQ AX, CX
	JCS  LessU_yes
	MOVQ $0x0000000000000000, AX
	JMP  LessU_end

LessU_yes:
	MOVQ $0x0000000000000001, AX

LessU_end:
	MOVQ AX, ret+16(FP)
	RET

// func AboveU(a uint64, b uint64) uint64
TEXT ·AboveU(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPQ AX, CX
	JHI  AboveU_yes
	MOVQ $0x0000000000000000, AX
	JMP  AboveU_end

AboveU_yes:
	MOVQ $0x0000000000000001, AX

AboveU_end:
	MOVQ AX, ret+16(FP)
	RET

// func Equal(a uint64, b uint64) uint64
TEXT ·Equal(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPQ AX, CX
	JEQ  Equal_yes
	MOVQ $0x0000000000000000, AX
	JMP  Equal_end

Equal_yes:
	MOVQ $0x0000000000000001, AX

Equal_end:
	MOVQ AX, ret+16(FP)
	RET

// func SelectEq(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelectEq(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQEQ DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func SubGapEq(x uint64, y uint64) uint64
TEXT ·SubGapEq(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	SUBQ CX, AX
	MOVQ $0x0000000000000000, AX
	JEQ  SubGapEq_yes
	JMP  SubGapEq_end

SubGapEq_yes:
	MOVQ $0x0000000000000001, AX

SubGapEq_end:
	MOVQ AX, ret+16(FP)
	RET

// func DecGapZero(x uint64, y uint64) uint64
TEXT ·DecGapZero(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	DECQ AX
	MOVQ $0x0000000000000000, AX
	JEQ  DecGapZero_yes
	JMP  DecGapZero_end

DecGapZero_yes:
	MOVQ $0x0000000000000001, AX

DecGapZero_end:
	MOVQ AX, ret+16(FP)
	RET

// func CmpL32Eq(a uint64, b uint64) uint64
TEXT ·CmpL32Eq(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPL AX, CX
	JEQ  CmpL32Eq_yes
	MOVQ $0x0000000000000000, AX
	JMP  CmpL32Eq_end

CmpL32Eq_yes:
	MOVQ $0x0000000000000001, AX

CmpL32Eq_end:
	MOVQ AX, ret+16(FP)
	RET

// func CmpL32LessS(a uint64, b uint64) uint64
TEXT ·CmpL32LessS(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPL AX, CX
	JLT  CmpL32LessS_yes
	MOVQ $0x0000000000000000, AX
	JMP  CmpL32LessS_end

CmpL32LessS_yes:
	MOVQ $0x0000000000000001, AX

CmpL32LessS_end:
	MOVQ AX, ret+16(FP)
	RET

// func CmpL32LessU(a uint64, b uint64) uint64
TEXT ·CmpL32LessU(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPL AX, CX
	JCS  CmpL32LessU_yes
	MOVQ $0x0000000000000000, AX
	JMP  CmpL32LessU_end

CmpL32LessU_yes:
	MOVQ $0x0000000000000001, AX

CmpL32LessU_end:
	MOVQ AX, ret+16(FP)
	RET

// func TestL32(a uint64, m uint64) uint64
TEXT ·TestL32(SB), NOSPLIT, $0-24
	MOVQ  a+0(FP), AX
	MOVQ  m+8(FP), CX
	TESTL AX, CX
	JEQ   TestL32_zero
	MOVQ  $0x0000000000000000, AX
	JMP   TestL32_end

TestL32_zero:
	MOVQ $0x0000000000000001, AX

TestL32_end:
	MOVQ AX, ret+16(FP)
	RET

// func CmpW16Eq(a uint64, b uint64) uint64
TEXT ·CmpW16Eq(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPW AX, CX
	JEQ  CmpW16Eq_yes
	MOVQ $0x0000000000000000, AX
	JMP  CmpW16Eq_end

CmpW16Eq_yes:
	MOVQ $0x0000000000000001, AX

CmpW16Eq_end:
	MOVQ AX, ret+16(FP)
	RET

// func CmpB8Ne(a uint64, b uint64) uint64
TEXT ·CmpB8Ne(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPB AL, CL
	JNE  CmpB8Ne_diff
	MOVQ $0x0000000000000000, AX
	JMP  CmpB8Ne_end

CmpB8Ne_diff:
	MOVQ $0x0000000000000001, AX

CmpB8Ne_end:
	MOVQ AX, ret+16(FP)
	RET

// func TestW16Eq(a uint64, m uint64) uint64
TEXT ·TestW16Eq(SB), NOSPLIT, $0-24
	MOVQ  a+0(FP), AX
	MOVQ  m+8(FP), CX
	TESTW AX, CX
	JEQ   TestW16Eq_zero
	MOVQ  $0x0000000000000000, AX
	JMP   TestW16Eq_end

TestW16Eq_zero:
	MOVQ $0x0000000000000001, AX

TestW16Eq_end:
	MOVQ AX, ret+16(FP)
	RET

// func IMul2(x uint64, y uint64) uint64
TEXT ·IMul2(SB), NOSPLIT, $0-24
	MOVQ  x+0(FP), AX
	MOVQ  y+8(FP), CX
	IMULQ AX, CX
	MOVQ  CX, ret+16(FP)
	RET

// func IMul3(x uint64) uint64
TEXT ·IMul3(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	IMUL3Q $0x9e3779b1, AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func MulWide(x uint64, y uint64) (lo uint64, hi uint64)
TEXT ·MulWide(SB), NOSPLIT, $0-32
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), SI
	MULQ SI
	MOVQ AX, lo+16(FP)
	MOVQ DX, hi+24(FP)
	RET

// func IMulWide(x int64, y int64) (lo uint64, hi uint64)
TEXT ·IMulWide(SB), NOSPLIT, $0-32
	MOVQ  x+0(FP), AX
	MOVQ  y+8(FP), SI
	IMULQ SI
	MOVQ  AX, lo+16(FP)
	MOVQ  DX, hi+24(FP)
	RET

// func MulX(x uint64, y uint64) (lo uint64, hi uint64)
// Requires: BMI2
TEXT ·MulX(SB), NOSPLIT, $0-32
	MOVQ  x+0(FP), SI
	MOVQ  y+8(FP), DX
	MULXQ SI, AX, BX
	MOVQ  AX, lo+16(FP)
	MOVQ  BX, hi+24(FP)
	RET

// func ShlX(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·ShlX(SB), NOSPLIT, $0-24
	MOVQ  x+0(FP), AX
	MOVQ  n+8(FP), CX
	SHLXQ CX, AX, AX
	MOVQ  AX, ret+16(FP)
	RET

// func ShrX(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·ShrX(SB), NOSPLIT, $0-24
	MOVQ  x+0(FP), AX
	MOVQ  n+8(FP), CX
	SHRXQ CX, AX, AX
	MOVQ  AX, ret+16(FP)
	RET

// func SarX(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·SarX(SB), NOSPLIT, $0-24
	MOVQ  x+0(FP), AX
	MOVQ  n+8(FP), CX
	SARXQ CX, AX, AX
	MOVQ  AX, ret+16(FP)
	RET

// func RorX(x uint64) uint64
// Requires: BMI2
TEXT ·RorX(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	RORXQ $0x38, AX, AX
	MOVQ  AX, ret+8(FP)
	RET

// func Bzhi(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·Bzhi(SB), NOSPLIT, $0-24
	MOVQ  x+0(FP), AX
	MOVQ  n+8(FP), CX
	BZHIQ CX, AX, AX
	MOVQ  AX, ret+16(FP)
	RET

// func Bextr88(x uint64) uint64
// Requires: BMI
TEXT ·Bextr88(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	MOVQ   $0x00000808, CX
	BEXTRQ CX, AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func Bextr4_12(x uint64) uint64
// Requires: BMI
TEXT ·Bextr4_12(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	MOVQ   $0x00000c04, CX
	BEXTRQ CX, AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func Bextr56_8(x uint64) uint64
// Requires: BMI
TEXT ·Bextr56_8(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	MOVQ   $0x00000838, CX
	BEXTRQ CX, AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func Bextr8_56(x uint64) uint64
// Requires: BMI
TEXT ·Bextr8_56(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	MOVQ   $0x00003808, CX
	BEXTRQ CX, AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func Bextr8_60(x uint64) uint64
// Requires: BMI
TEXT ·Bextr8_60(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	MOVQ   $0x00003c08, CX
	BEXTRQ CX, AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func Bextr0_0(x uint64) uint64
// Requires: BMI
TEXT ·Bextr0_0(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	MOVQ   $0x00000000, CX
	BEXTRQ CX, AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func Bextr70_8(x uint64) uint64
// Requires: BMI
TEXT ·Bextr70_8(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	MOVQ   $0x00000846, CX
	BEXTRQ CX, AX, AX
	MOVQ   AX, ret+8(FP)
	RET

// func BzhiConst13(x uint64) uint64
// Requires: BMI2
TEXT ·BzhiConst13(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	MOVQ  $0x0000000d, CX
	BZHIQ CX, AX, AX
	MOVQ  AX, ret+8(FP)
	RET

// func BzhiConst0(x uint64) uint64
// Requires: BMI2
TEXT ·BzhiConst0(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	MOVQ  $0x00000000, CX
	BZHIQ CX, AX, AX
	MOVQ  AX, ret+8(FP)
	RET

// func BzhiConst64(x uint64) uint64
// Requires: BMI2
TEXT ·BzhiConst64(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	MOVQ  $0x00000040, CX
	BZHIQ CX, AX, AX
	MOVQ  AX, ret+8(FP)
	RET

// func ShlXConst9(x uint64) uint64
// Requires: BMI2
TEXT ·ShlXConst9(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	MOVQ  $0x00000009, CX
	SHLXQ CX, AX, AX
	MOVQ  AX, ret+8(FP)
	RET

// func ShrXConst9(x uint64) uint64
// Requires: BMI2
TEXT ·ShrXConst9(SB), NOSPLIT, $0-16
	MOVQ  x+0(FP), AX
	MOVQ  $0x00000009, CX
	SHRXQ CX, AX, AX
	MOVQ  AX, ret+8(FP)
	RET

// func SetGe(a uint64, b uint64) uint64
TEXT ·SetGe(SB), NOSPLIT, $0-24
	MOVQ  a+0(FP), AX
	MOVQ  b+8(FP), CX
	XORL  DX, DX
	CMPQ  AX, CX
	SETGE DL
	MOVQ  DX, ret+16(FP)
	RET

// func AdcAccum(x uint64, acc uint64) uint64
TEXT ·AdcAccum(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ acc+8(FP), CX
	CMPQ AX, $0x04
	ADCB $+0, CL
	MOVQ CX, ret+16(FP)
	RET

// func BswapL(x uint64) uint64
TEXT ·BswapL(SB), NOSPLIT, $0-16
	MOVQ   x+0(FP), AX
	BSWAPL AX
	MOVQ   AX, ret+8(FP)
	RET

// func AddByte(x uint64, y uint64) uint64
TEXT ·AddByte(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	ADDB AL, CL
	MOVQ CX, ret+16(FP)
	RET

// func MovbHighDst(x uint64, y uint64) uint64
TEXT ·MovbHighDst(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), CX
	MOVQ y+8(FP), AX
	MOVB CL, AH
	MOVQ AX, ret+16(FP)
	RET

// func MovbLowPreserve(x uint64, y uint64) uint64
TEXT ·MovbLowPreserve(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), CX
	MOVQ y+8(FP), AX
	MOVB CH, AL
	MOVQ AX, ret+16(FP)
	RET

// func SelLtS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelLtS(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQLT DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func SelLeS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelLeS(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQLE DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func SelGtS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelGtS(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQGT DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func SelGeS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelGeS(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQGE DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func SelLsU(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelLsU(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQLS DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func SelMi(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelMi(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQMI DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func SelPl(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelPl(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQPL DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func StackAccum(x uint64, n uint64) uint64
TEXT ·StackAccum(SB), NOSPLIT, $16-24
	MOVQ x+0(FP), AX
	MOVQ n+8(FP), CX
	XORQ DX, DX
	MOVQ DX, (SP)
	MOVQ CX, 8(SP)

accum_loop:
	MOVQ  8(SP), CX
	TESTQ CX, CX
	JZ    accum_done
	MOVQ  (SP), DX
	ADDQ  AX, DX
	MOVQ  DX, (SP)
	INCQ  AX
	DECQ  CX
	MOVQ  CX, 8(SP)
	JMP   accum_loop

accum_done:
	MOVQ (SP), AX
	MOVQ AX, ret+16(FP)
	RET

// func ManySlotAccum(x uint64) uint64
TEXT ·ManySlotAccum(SB), NOSPLIT, $96-16
	MOVQ x+0(FP), AX
	MOVQ AX, CX
	ADDQ $0x00000000, CX
	MOVQ CX, (SP)
	MOVQ AX, CX
	ADDQ $0x00000001, CX
	MOVQ CX, 8(SP)
	MOVQ AX, CX
	ADDQ $0x00000002, CX
	MOVQ CX, 16(SP)
	MOVQ AX, CX
	ADDQ $0x00000003, CX
	MOVQ CX, 24(SP)
	MOVQ AX, CX
	ADDQ $0x00000004, CX
	MOVQ CX, 32(SP)
	MOVQ AX, CX
	ADDQ $0x00000005, CX
	MOVQ CX, 40(SP)
	MOVQ AX, CX
	ADDQ $0x00000006, CX
	MOVQ CX, 48(SP)
	MOVQ AX, CX
	ADDQ $0x00000007, CX
	MOVQ CX, 56(SP)
	MOVQ AX, CX
	ADDQ $0x00000008, CX
	MOVQ CX, 64(SP)
	MOVQ AX, CX
	ADDQ $0x00000009, CX
	MOVQ CX, 72(SP)
	MOVQ AX, CX
	ADDQ $0x0000000a, CX
	MOVQ CX, 80(SP)
	ADDQ $0x0000000b, AX
	MOVQ AX, 88(SP)
	MOVQ (SP), AX
	ADDQ $0x00000001, AX
	MOVQ AX, (SP)
	MOVQ (SP), AX
	ADDQ $0x00000002, AX
	MOVQ AX, (SP)
	MOVQ (SP), AX
	ADDQ $0x00000003, AX
	MOVQ AX, (SP)
	MOVQ (SP), AX
	ADDQ $0x00000004, AX
	MOVQ AX, (SP)
	MOVQ (SP), AX
	ADDQ $0x00000005, AX
	MOVQ AX, (SP)
	MOVQ (SP), AX
	ADDQ $0x00000006, AX
	MOVQ AX, (SP)
	MOVQ (SP), AX
	ADDQ $0x00000007, AX
	MOVQ AX, (SP)
	MOVQ (SP), AX
	ADDQ $0x00000008, AX
	MOVQ AX, (SP)
	MOVQ (SP), AX
	ADDQ $0x00000009, AX
	MOVQ AX, (SP)
	MOVQ (SP), AX
	ADDQ $0x0000000a, AX
	MOVQ AX, (SP)
	MOVQ (SP), AX
	ADDQ $0x0000000b, AX
	MOVQ AX, (SP)
	MOVQ (SP), AX
	ADDQ $0x0000000c, AX
	MOVQ AX, (SP)
	MOVQ 8(SP), AX
	ADDQ $0x00000001, AX
	MOVQ AX, 8(SP)
	MOVQ 8(SP), AX
	ADDQ $0x00000002, AX
	MOVQ AX, 8(SP)
	MOVQ 8(SP), AX
	ADDQ $0x00000003, AX
	MOVQ AX, 8(SP)
	MOVQ 8(SP), AX
	ADDQ $0x00000004, AX
	MOVQ AX, 8(SP)
	MOVQ 8(SP), AX
	ADDQ $0x00000005, AX
	MOVQ AX, 8(SP)
	MOVQ 8(SP), AX
	ADDQ $0x00000006, AX
	MOVQ AX, 8(SP)
	MOVQ 8(SP), AX
	ADDQ $0x00000007, AX
	MOVQ AX, 8(SP)
	MOVQ 8(SP), AX
	ADDQ $0x00000008, AX
	MOVQ AX, 8(SP)
	MOVQ 8(SP), AX
	ADDQ $0x00000009, AX
	MOVQ AX, 8(SP)
	MOVQ 8(SP), AX
	ADDQ $0x0000000a, AX
	MOVQ AX, 8(SP)
	MOVQ 8(SP), AX
	ADDQ $0x0000000b, AX
	MOVQ AX, 8(SP)
	MOVQ 16(SP), AX
	ADDQ $0x00000001, AX
	MOVQ AX, 16(SP)
	MOVQ 16(SP), AX
	ADDQ $0x00000002, AX
	MOVQ AX, 16(SP)
	MOVQ 16(SP), AX
	ADDQ $0x00000003, AX
	MOVQ AX, 16(SP)
	MOVQ 16(SP), AX
	ADDQ $0x00000004, AX
	MOVQ AX, 16(SP)
	MOVQ 16(SP), AX
	ADDQ $0x00000005, AX
	MOVQ AX, 16(SP)
	MOVQ 16(SP), AX
	ADDQ $0x00000006, AX
	MOVQ AX, 16(SP)
	MOVQ 16(SP), AX
	ADDQ $0x00000007, AX
	MOVQ AX, 16(SP)
	MOVQ 16(SP), AX
	ADDQ $0x00000008, AX
	MOVQ AX, 16(SP)
	MOVQ 16(SP), AX
	ADDQ $0x00000009, AX
	MOVQ AX, 16(SP)
	MOVQ 16(SP), AX
	ADDQ $0x0000000a, AX
	MOVQ AX, 16(SP)
	MOVQ 24(SP), AX
	ADDQ $0x00000001, AX
	MOVQ AX, 24(SP)
	MOVQ 24(SP), AX
	ADDQ $0x00000002, AX
	MOVQ AX, 24(SP)
	MOVQ 24(SP), AX
	ADDQ $0x00000003, AX
	MOVQ AX, 24(SP)
	MOVQ 24(SP), AX
	ADDQ $0x00000004, AX
	MOVQ AX, 24(SP)
	MOVQ 24(SP), AX
	ADDQ $0x00000005, AX
	MOVQ AX, 24(SP)
	MOVQ 24(SP), AX
	ADDQ $0x00000006, AX
	MOVQ AX, 24(SP)
	MOVQ 24(SP), AX
	ADDQ $0x00000007, AX
	MOVQ AX, 24(SP)
	MOVQ 24(SP), AX
	ADDQ $0x00000008, AX
	MOVQ AX, 24(SP)
	MOVQ 24(SP), AX
	ADDQ $0x00000009, AX
	MOVQ AX, 24(SP)
	MOVQ 32(SP), AX
	ADDQ $0x00000001, AX
	MOVQ AX, 32(SP)
	MOVQ 32(SP), AX
	ADDQ $0x00000002, AX
	MOVQ AX, 32(SP)
	MOVQ 32(SP), AX
	ADDQ $0x00000003, AX
	MOVQ AX, 32(SP)
	MOVQ 32(SP), AX
	ADDQ $0x00000004, AX
	MOVQ AX, 32(SP)
	MOVQ 32(SP), AX
	ADDQ $0x00000005, AX
	MOVQ AX, 32(SP)
	MOVQ 32(SP), AX
	ADDQ $0x00000006, AX
	MOVQ AX, 32(SP)
	MOVQ 32(SP), AX
	ADDQ $0x00000007, AX
	MOVQ AX, 32(SP)
	MOVQ 32(SP), AX
	ADDQ $0x00000008, AX
	MOVQ AX, 32(SP)
	MOVQ 40(SP), AX
	ADDQ $0x00000001, AX
	MOVQ AX, 40(SP)
	MOVQ 40(SP), AX
	ADDQ $0x00000002, AX
	MOVQ AX, 40(SP)
	MOVQ 40(SP), AX
	ADDQ $0x00000003, AX
	MOVQ AX, 40(SP)
	MOVQ 40(SP), AX
	ADDQ $0x00000004, AX
	MOVQ AX, 40(SP)
	MOVQ 40(SP), AX
	ADDQ $0x00000005, AX
	MOVQ AX, 40(SP)
	MOVQ 40(SP), AX
	ADDQ $0x00000006, AX
	MOVQ AX, 40(SP)
	MOVQ 40(SP), AX
	ADDQ $0x00000007, AX
	MOVQ AX, 40(SP)
	MOVQ 48(SP), AX
	ADDQ $0x00000001, AX
	MOVQ AX, 48(SP)
	MOVQ 48(SP), AX
	ADDQ $0x00000002, AX
	MOVQ AX, 48(SP)
	MOVQ 48(SP), AX
	ADDQ $0x00000003, AX
	MOVQ AX, 48(SP)
	MOVQ 48(SP), AX
	ADDQ $0x00000004, AX
	MOVQ AX, 48(SP)
	MOVQ 48(SP), AX
	ADDQ $0x00000005, AX
	MOVQ AX, 48(SP)
	MOVQ 48(SP), AX
	ADDQ $0x00000006, AX
	MOVQ AX, 48(SP)
	MOVQ 56(SP), AX
	ADDQ $0x00000001, AX
	MOVQ AX, 56(SP)
	MOVQ 56(SP), AX
	ADDQ $0x00000002, AX
	MOVQ AX, 56(SP)
	MOVQ 56(SP), AX
	ADDQ $0x00000003, AX
	MOVQ AX, 56(SP)
	MOVQ 56(SP), AX
	ADDQ $0x00000004, AX
	MOVQ AX, 56(SP)
	MOVQ 56(SP), AX
	ADDQ $0x00000005, AX
	MOVQ AX, 56(SP)
	MOVQ 64(SP), AX
	ADDQ $0x00000001, AX
	MOVQ AX, 64(SP)
	MOVQ 64(SP), AX
	ADDQ $0x00000002, AX
	MOVQ AX, 64(SP)
	MOVQ 64(SP), AX
	ADDQ $0x00000003, AX
	MOVQ AX, 64(SP)
	MOVQ 64(SP), AX
	ADDQ $0x00000004, AX
	MOVQ AX, 64(SP)
	MOVQ 72(SP), AX
	ADDQ $0x00000001, AX
	MOVQ AX, 72(SP)
	MOVQ 72(SP), AX
	ADDQ $0x00000002, AX
	MOVQ AX, 72(SP)
	MOVQ 72(SP), AX
	ADDQ $0x00000003, AX
	MOVQ AX, 72(SP)
	MOVQ 80(SP), AX
	ADDQ $0x00000001, AX
	MOVQ AX, 80(SP)
	MOVQ 80(SP), AX
	ADDQ $0x00000002, AX
	MOVQ AX, 80(SP)
	MOVQ 88(SP), AX
	ADDQ $0x00000001, AX
	MOVQ AX, 88(SP)
	XORQ AX, AX
	MOVQ (SP), CX
	ADDQ CX, AX
	MOVQ 8(SP), CX
	ADDQ CX, AX
	MOVQ 16(SP), CX
	ADDQ CX, AX
	MOVQ 24(SP), CX
	ADDQ CX, AX
	MOVQ 32(SP), CX
	ADDQ CX, AX
	MOVQ 40(SP), CX
	ADDQ CX, AX
	MOVQ 48(SP), CX
	ADDQ CX, AX
	MOVQ 56(SP), CX
	ADDQ CX, AX
	MOVQ 64(SP), CX
	ADDQ CX, AX
	MOVQ 72(SP), CX
	ADDQ CX, AX
	MOVQ 80(SP), CX
	ADDQ CX, AX
	MOVQ 88(SP), CX
	ADDQ CX, AX
	MOVQ AX, ret+8(FP)
	RET
