// Code generated by command: go run asm.go -out lower_amd64.s -arm64 lower_arm64.s -stubs stub.go. DO NOT EDIT.
// EXPERIMENTAL arm64 output lowered from an amd64 avo program.

//go:build arm64

#include "textflag.h"

// func Add(x uint64, y uint64) uint64
TEXT ·Add(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ADD  R0, R1, R1
	MOVD R1, ret+16(FP)
	RET

// func Sub(x uint64, y uint64) uint64
TEXT ·Sub(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	SUB  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Neg(x uint64) uint64
TEXT ·Neg(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	NEG  R0, R0
	MOVD R0, ret+8(FP)
	RET

// func AndOrXor(x uint64, y uint64) uint64
TEXT ·AndOrXor(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MOVD R0, R2
	AND  R1, R2, R2
	ORR  R1, R0, R0
	EOR  R0, R2, R2
	MOVD R2, ret+16(FP)
	RET

// func ShlCL(x uint64, n uint64) uint64
TEXT ·ShlCL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	LSL  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func ShrCL(x uint64, n uint64) uint64
TEXT ·ShrCL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	LSR  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func RolCL(x uint64, n uint64) uint64
TEXT ·RolCL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	NEG  R1, R16
	ROR  R16, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func ZeroExt32(x uint64) uint64
TEXT ·ZeroExt32(SB), NOSPLIT, $0-16
	MOVD  x+0(FP), R0
	MOVWU R0, R1
	ADD   R0, R1, R1
	MOVD  R1, ret+8(FP)
	RET

// func HighByte(x uint64) uint64
TEXT ·HighByte(SB), NOSPLIT, $0-16
	MOVD  x+0(FP), R0
	UBFX  $8, R0, $8, R16
	BFI   $0, R16, $8, R0
	MOVBU R0, R0
	MOVD  R0, ret+8(FP)
	RET

// func LoadIdx(p *[8]uint64, i uint64) uint64
TEXT ·LoadIdx(SB), NOSPLIT, $0-24
	MOVD p+0(FP), R0
	MOVD i+8(FP), R1
	ADD  R1<<3, R0, R15
	MOVD (R15), R0
	MOVD R0, ret+16(FP)
	RET

// func Copy16(dst *[16]byte, src *[16]byte)
// Requires: SSE
TEXT ·Copy16(SB), NOSPLIT, $0-16
	MOVD dst+0(FP), R0
	MOVD src+8(FP), R1
	VLD1 (R1), [V0.B16]
	VST1 [V0.B16], (R0)
	RET

// func LessS(a uint64, b uint64) uint64
TEXT ·LessS(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	BLT  LessS_yes
	MOVD $0x0000000000000000, R0
	JMP  LessS_end

LessS_yes:
	MOVD $0x0000000000000001, R0

LessS_end:
	MOVD R0, ret+16(FP)
	RET

// func GreaterEqS(a uint64, b uint64) uint64
TEXT ·GreaterEqS(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	BGE  GreaterEqS_yes
	MOVD $0x0000000000000000, R0
	JMP  GreaterEqS_end

GreaterEqS_yes:
	MOVD $0x0000000000000001, R0

GreaterEqS_end:
	MOVD R0, ret+16(FP)
	RET

// func LessU(a uint64, b uint64) uint64
TEXT ·LessU(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	BLO  LessU_yes
	MOVD $0x0000000000000000, R0
	JMP  LessU_end

LessU_yes:
	MOVD $0x0000000000000001, R0

LessU_end:
	MOVD R0, ret+16(FP)
	RET

// func AboveU(a uint64, b uint64) uint64
TEXT ·AboveU(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	BHI  AboveU_yes
	MOVD $0x0000000000000000, R0
	JMP  AboveU_end

AboveU_yes:
	MOVD $0x0000000000000001, R0

AboveU_end:
	MOVD R0, ret+16(FP)
	RET

// func Equal(a uint64, b uint64) uint64
TEXT ·Equal(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	BEQ  Equal_yes
	MOVD $0x0000000000000000, R0
	JMP  Equal_end

Equal_yes:
	MOVD $0x0000000000000001, R0

Equal_end:
	MOVD R0, ret+16(FP)
	RET

// func SelectEq(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelectEq(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL EQ, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SubGapEq(x uint64, y uint64) uint64
TEXT ·SubGapEq(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	SUBS R1, R0, R0
	MOVD $0x0000000000000000, R0
	BEQ  SubGapEq_yes
	JMP  SubGapEq_end

SubGapEq_yes:
	MOVD $0x0000000000000001, R0

SubGapEq_end:
	MOVD R0, ret+16(FP)
	RET

// func DecGapZero(x uint64, y uint64) uint64
TEXT ·DecGapZero(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	SUBS $1, R0, R0
	MOVD $0x0000000000000000, R0
	BEQ  DecGapZero_yes
	JMP  DecGapZero_end

DecGapZero_yes:
	MOVD $0x0000000000000001, R0

DecGapZero_end:
	MOVD R0, ret+16(FP)
	RET

// func CmpL32Eq(a uint64, b uint64) uint64
TEXT ·CmpL32Eq(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMPW R1, R0
	BEQ  CmpL32Eq_yes
	MOVD $0x0000000000000000, R0
	JMP  CmpL32Eq_end

CmpL32Eq_yes:
	MOVD $0x0000000000000001, R0

CmpL32Eq_end:
	MOVD R0, ret+16(FP)
	RET

// func CmpL32LessS(a uint64, b uint64) uint64
TEXT ·CmpL32LessS(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMPW R1, R0
	BLT  CmpL32LessS_yes
	MOVD $0x0000000000000000, R0
	JMP  CmpL32LessS_end

CmpL32LessS_yes:
	MOVD $0x0000000000000001, R0

CmpL32LessS_end:
	MOVD R0, ret+16(FP)
	RET

// func CmpL32LessU(a uint64, b uint64) uint64
TEXT ·CmpL32LessU(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMPW R1, R0
	BLO  CmpL32LessU_yes
	MOVD $0x0000000000000000, R0
	JMP  CmpL32LessU_end

CmpL32LessU_yes:
	MOVD $0x0000000000000001, R0

CmpL32LessU_end:
	MOVD R0, ret+16(FP)
	RET

// func TestL32(a uint64, m uint64) uint64
TEXT ·TestL32(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD m+8(FP), R1
	TSTW R1, R0
	BEQ  TestL32_zero
	MOVD $0x0000000000000000, R0
	JMP  TestL32_end

TestL32_zero:
	MOVD $0x0000000000000001, R0

TestL32_end:
	MOVD R0, ret+16(FP)
	RET

// func CmpW16Eq(a uint64, b uint64) uint64
TEXT ·CmpW16Eq(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	AND  $0xffff, R0, R15
	AND  $0xffff, R1, R16
	CMP  R16, R15
	BEQ  CmpW16Eq_yes
	MOVD $0x0000000000000000, R0
	JMP  CmpW16Eq_end

CmpW16Eq_yes:
	MOVD $0x0000000000000001, R0

CmpW16Eq_end:
	MOVD R0, ret+16(FP)
	RET

// func CmpB8Ne(a uint64, b uint64) uint64
TEXT ·CmpB8Ne(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	AND  $0xff, R0, R15
	AND  $0xff, R1, R16
	CMP  R16, R15
	BNE  CmpB8Ne_diff
	MOVD $0x0000000000000000, R0
	JMP  CmpB8Ne_end

CmpB8Ne_diff:
	MOVD $0x0000000000000001, R0

CmpB8Ne_end:
	MOVD R0, ret+16(FP)
	RET

// func TestW16Eq(a uint64, m uint64) uint64
TEXT ·TestW16Eq(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD m+8(FP), R1
	AND  $0xffff, R0, R15
	AND  $0xffff, R1, R16
	TST  R16, R15
	BEQ  TestW16Eq_zero
	MOVD $0x0000000000000000, R0
	JMP  TestW16Eq_end

TestW16Eq_zero:
	MOVD $0x0000000000000001, R0

TestW16Eq_end:
	MOVD R0, ret+16(FP)
	RET

// func IMul2(x uint64, y uint64) uint64
TEXT ·IMul2(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MUL  R0, R1, R1
	MOVD R1, ret+16(FP)
	RET

// func IMul3(x uint64) uint64
TEXT ·IMul3(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $-1640531535, R16
	MUL  R16, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func MulWide(x uint64, y uint64) (lo uint64, hi uint64)
TEXT ·MulWide(SB), NOSPLIT, $0-32
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R5
	UMULH R5, R0, R2
	MUL   R5, R0, R0
	MOVD  R0, lo+16(FP)
	MOVD  R2, hi+24(FP)
	RET

// func IMulWide(x int64, y int64) (lo uint64, hi uint64)
TEXT ·IMulWide(SB), NOSPLIT, $0-32
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R5
	SMULH R5, R0, R2
	MUL   R5, R0, R0
	MOVD  R0, lo+16(FP)
	MOVD  R2, hi+24(FP)
	RET

// func MulX(x uint64, y uint64) (lo uint64, hi uint64)
// Requires: BMI2
TEXT ·MulX(SB), NOSPLIT, $0-32
	MOVD  x+0(FP), R5
	MOVD  y+8(FP), R2
	MUL   R5, R2, R16
	UMULH R5, R2, R3
	MOVD  R16, R0
	MOVD  R0, lo+16(FP)
	MOVD  R3, hi+24(FP)
	RET

// func ShlX(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·ShlX(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	LSL  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func ShrX(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·ShrX(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	LSR  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func SarX(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·SarX(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	ASR  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func RorX(x uint64) uint64
// Requires: BMI2
TEXT ·RorX(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	ROR  $56, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func Bzhi(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·Bzhi(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	MOVD $1, R16
	LSL  R1, R16, R16
	SUB  $1, R16, R16
	AND  R16, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Bextr88(x uint64) uint64
// Requires: BMI
TEXT ·Bextr88(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000808, R1
	UBFX $0, R1, $8, R16
	UBFX $8, R1, $8, R15
	LSR  R16, R0, R0
	MOVD $1, R16
	LSL  R15, R16, R16
	SUB  $1, R16, R16
	AND  R16, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func Bextr4_12(x uint64) uint64
// Requires: BMI
TEXT ·Bextr4_12(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000c04, R1
	UBFX $0, R1, $8, R16
	UBFX $8, R1, $8, R15
	LSR  R16, R0, R0
	MOVD $1, R16
	LSL  R15, R16, R16
	SUB  $1, R16, R16
	AND  R16, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func MovbHighDst(x uint64, y uint64) uint64
TEXT ·MovbHighDst(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R1
	MOVD y+8(FP), R0
	BFI  $8, R1, $8, R0
	MOVD R0, ret+16(FP)
	RET

// func MovbLowPreserve(x uint64, y uint64) uint64
TEXT ·MovbLowPreserve(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R1
	MOVD y+8(FP), R0
	UBFX $8, R1, $8, R16
	BFI  $0, R16, $8, R0
	MOVD R0, ret+16(FP)
	RET

// func SelLtS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelLtS(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL LT, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelLeS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelLeS(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL LE, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelGtS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelGtS(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL GT, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelGeS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelGeS(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL GE, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelLsU(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelLsU(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL LS, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelMi(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelMi(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL MI, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelPl(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelPl(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL PL, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET
