// Code generated by command: go run asm.go -out lower_amd64.s -arm64 lower_arm64.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

// func Add(x uint64, y uint64) uint64
TEXT ·Add(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	ADDQ AX, CX
	MOVQ CX, ret+16(FP)
	RET

// func Sub(x uint64, y uint64) uint64
TEXT ·Sub(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	SUBQ CX, AX
	MOVQ AX, ret+16(FP)
	RET

// func Neg(x uint64) uint64
TEXT ·Neg(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	NEGQ AX
	MOVQ AX, ret+8(FP)
	RET

// func AndOrXor(x uint64, y uint64) uint64
TEXT ·AndOrXor(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	MOVQ AX, DX
	ANDQ CX, DX
	ORQ  CX, AX
	XORQ AX, DX
	MOVQ DX, ret+16(FP)
	RET

// func ShlCL(x uint64, n uint64) uint64
TEXT ·ShlCL(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ n+8(FP), CX
	SHLQ CL, AX
	MOVQ AX, ret+16(FP)
	RET

// func ShrCL(x uint64, n uint64) uint64
TEXT ·ShrCL(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ n+8(FP), CX
	SHRQ CL, AX
	MOVQ AX, ret+16(FP)
	RET

// func RolCL(x uint64, n uint64) uint64
TEXT ·RolCL(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ n+8(FP), CX
	ROLQ CL, AX
	MOVQ AX, ret+16(FP)
	RET

// func ZeroExt32(x uint64) uint64
TEXT ·ZeroExt32(SB), NOSPLIT, $0-16
	MOVQ x+0(FP), AX
	MOVL AX, CX
	ADDQ AX, CX
	MOVQ CX, ret+8(FP)
	RET

// func HighByte(x uint64) uint64
TEXT ·HighByte(SB), NOSPLIT, $0-16
	MOVQ    x+0(FP), AX
	MOVB    AH, AL
	MOVBQZX AL, AX
	MOVQ    AX, ret+8(FP)
	RET

// func LoadIdx(p *[8]uint64, i uint64) uint64
TEXT ·LoadIdx(SB), NOSPLIT, $0-24
	MOVQ p+0(FP), AX
	MOVQ i+8(FP), CX
	MOVQ (AX)(CX*8), AX
	MOVQ AX, ret+16(FP)
	RET

// func Copy16(dst *[16]byte, src *[16]byte)
// Requires: SSE
TEXT ·Copy16(SB), NOSPLIT, $0-16
	MOVQ   dst+0(FP), AX
	MOVQ   src+8(FP), CX
	MOVUPS (CX), X0
	MOVUPS X0, (AX)
	RET

// func LessS(a uint64, b uint64) uint64
TEXT ·LessS(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPQ AX, CX
	JLT  LessS_yes
	MOVQ $0x0000000000000000, AX
	JMP  LessS_end

LessS_yes:
	MOVQ $0x0000000000000001, AX

LessS_end:
	MOVQ AX, ret+16(FP)
	RET

// func GreaterEqS(a uint64, b uint64) uint64
TEXT ·GreaterEqS(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPQ AX, CX
	JGE  GreaterEqS_yes
	MOVQ $0x0000000000000000, AX
	JMP  GreaterEqS_end

GreaterEqS_yes:
	MOVQ $0x0000000000000001, AX

GreaterEqS_end:
	MOVQ AX, ret+16(FP)
	RET

// func LessU(a uint64, b uint64) uint64
TEXT ·LessU(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPQ AX, CX
	JCS  LessU_yes
	MOVQ $0x0000000000000000, AX
	JMP  LessU_end

LessU_yes:
	MOVQ $0x0000000000000001, AX

LessU_end:
	MOVQ AX, ret+16(FP)
	RET

// func AboveU(a uint64, b uint64) uint64
TEXT ·AboveU(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPQ AX, CX
	JHI  AboveU_yes
	MOVQ $0x0000000000000000, AX
	JMP  AboveU_end

AboveU_yes:
	MOVQ $0x0000000000000001, AX

AboveU_end:
	MOVQ AX, ret+16(FP)
	RET

// func Equal(a uint64, b uint64) uint64
TEXT ·Equal(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPQ AX, CX
	JEQ  Equal_yes
	MOVQ $0x0000000000000000, AX
	JMP  Equal_end

Equal_yes:
	MOVQ $0x0000000000000001, AX

Equal_end:
	MOVQ AX, ret+16(FP)
	RET

// func SelectEq(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelectEq(SB), NOSPLIT, $0-40
	MOVQ    a+0(FP), AX
	MOVQ    b+8(FP), CX
	MOVQ    c+16(FP), DX
	MOVQ    d+24(FP), BX
	CMPQ    AX, CX
	CMOVQEQ DX, BX
	MOVQ    BX, ret+32(FP)
	RET

// func SubGapEq(x uint64, y uint64) uint64
TEXT ·SubGapEq(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), CX
	SUBQ CX, AX
	MOVQ $0x0000000000000000, AX
	JEQ  SubGapEq_yes
	JMP  SubGapEq_end

SubGapEq_yes:
	MOVQ $0x0000000000000001, AX

SubGapEq_end:
	MOVQ AX, ret+16(FP)
	RET

// func DecGapZero(x uint64, y uint64) uint64
TEXT ·DecGapZero(SB), NOSPLIT, $0-24
	MOVQ x+0(FP), AX
	DECQ AX
	MOVQ $0x0000000000000000, AX
	JEQ  DecGapZero_yes
	JMP  DecGapZero_end

DecGapZero_yes:
	MOVQ $0x0000000000000001, AX

DecGapZero_end:
	MOVQ AX, ret+16(FP)
	RET

// func CmpL32Eq(a uint64, b uint64) uint64
TEXT ·CmpL32Eq(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPL AX, CX
	JEQ  CmpL32Eq_yes
	MOVQ $0x0000000000000000, AX
	JMP  CmpL32Eq_end

CmpL32Eq_yes:
	MOVQ $0x0000000000000001, AX

CmpL32Eq_end:
	MOVQ AX, ret+16(FP)
	RET

// func CmpL32LessS(a uint64, b uint64) uint64
TEXT ·CmpL32LessS(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPL AX, CX
	JLT  CmpL32LessS_yes
	MOVQ $0x0000000000000000, AX
	JMP  CmpL32LessS_end

CmpL32LessS_yes:
	MOVQ $0x0000000000000001, AX

CmpL32LessS_end:
	MOVQ AX, ret+16(FP)
	RET

// func CmpL32LessU(a uint64, b uint64) uint64
TEXT ·CmpL32LessU(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	CMPL AX, CX
	JCS  CmpL32LessU_yes
	MOVQ $0x0000000000000000, AX
	JMP  CmpL32LessU_end

CmpL32LessU_yes:
	MOVQ $0x0000000000000001, AX

CmpL32LessU_end:
	MOVQ AX, ret+16(FP)
	RET

// func TestL32(a uint64, m uint64) uint64
TEXT ·TestL32(SB), NOSPLIT, $0-24
	MOVQ  a+0(FP), AX
	MOVQ  m+8(FP), CX
	TESTL AX, CX
	JEQ   TestL32_zero
	MOVQ  $0x0000000000000000, AX
	JMP   TestL32_end

TestL32_zero:
	MOVQ $0x0000000000000001, AX

TestL32_end:
	MOVQ AX, ret+16(FP)
	RET
