// Code generated by command: go run asm.go -out lower_amd64.s -arm64 lower_arm64.s -stubs stub.go. DO NOT EDIT.
// EXPERIMENTAL arm64 output lowered from an amd64 avo program.

//go:build arm64

#include "textflag.h"

// func Add(x uint64, y uint64) uint64
TEXT ·Add(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ADD  R0, R1, R1
	MOVD R1, ret+16(FP)
	RET

// func Sub(x uint64, y uint64) uint64
TEXT ·Sub(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	SUB  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Neg(x uint64) uint64
TEXT ·Neg(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	NEG  R0, R0
	MOVD R0, ret+8(FP)
	RET

// func AndOrXor(x uint64, y uint64) uint64
TEXT ·AndOrXor(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MOVD R0, R2
	AND  R1, R2, R2
	ORR  R1, R0, R0
	EOR  R0, R2, R2
	MOVD R2, ret+16(FP)
	RET

// func ShlCL(x uint64, n uint64) uint64
TEXT ·ShlCL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	LSL  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func ShrCL(x uint64, n uint64) uint64
TEXT ·ShrCL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	LSR  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func RolCL(x uint64, n uint64) uint64
TEXT ·RolCL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	NEG  R1, R16
	ROR  R16, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func ZeroExt32(x uint64) uint64
TEXT ·ZeroExt32(SB), NOSPLIT, $0-16
	MOVD  x+0(FP), R0
	MOVWU R0, R1
	ADD   R0, R1, R1
	MOVD  R1, ret+8(FP)
	RET

// func HighByte(x uint64) uint64
TEXT ·HighByte(SB), NOSPLIT, $0-16
	MOVD  x+0(FP), R0
	UBFX  $8, R0, $8, R16
	BFI   $0, R16, $8, R0
	MOVBU R0, R0
	MOVD  R0, ret+8(FP)
	RET

// func LoadIdx(p *[8]uint64, i uint64) uint64
TEXT ·LoadIdx(SB), NOSPLIT, $0-24
	MOVD p+0(FP), R0
	MOVD i+8(FP), R1
	MOVD (R0)(R1<<3), R0
	MOVD R0, ret+16(FP)
	RET

// func Copy16(dst *[16]byte, src *[16]byte)
// Requires: SSE
TEXT ·Copy16(SB), NOSPLIT, $0-16
	MOVD  dst+0(FP), R0
	MOVD  src+8(FP), R1
	FMOVQ (R1), F0
	FMOVQ F0, (R0)
	RET

// func LessS(a uint64, b uint64) uint64
TEXT ·LessS(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	BLT  LessS_yes
	MOVD $0x0000000000000000, R0
	JMP  LessS_end

LessS_yes:
	MOVD $0x0000000000000001, R0

LessS_end:
	MOVD R0, ret+16(FP)
	RET

// func GreaterEqS(a uint64, b uint64) uint64
TEXT ·GreaterEqS(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	BGE  GreaterEqS_yes
	MOVD $0x0000000000000000, R0
	JMP  GreaterEqS_end

GreaterEqS_yes:
	MOVD $0x0000000000000001, R0

GreaterEqS_end:
	MOVD R0, ret+16(FP)
	RET

// func LessU(a uint64, b uint64) uint64
TEXT ·LessU(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	BLO  LessU_yes
	MOVD $0x0000000000000000, R0
	JMP  LessU_end

LessU_yes:
	MOVD $0x0000000000000001, R0

LessU_end:
	MOVD R0, ret+16(FP)
	RET

// func AboveU(a uint64, b uint64) uint64
TEXT ·AboveU(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	BHI  AboveU_yes
	MOVD $0x0000000000000000, R0
	JMP  AboveU_end

AboveU_yes:
	MOVD $0x0000000000000001, R0

AboveU_end:
	MOVD R0, ret+16(FP)
	RET

// func Equal(a uint64, b uint64) uint64
TEXT ·Equal(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMP  R1, R0
	BEQ  Equal_yes
	MOVD $0x0000000000000000, R0
	JMP  Equal_end

Equal_yes:
	MOVD $0x0000000000000001, R0

Equal_end:
	MOVD R0, ret+16(FP)
	RET

// func SelectEq(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelectEq(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL EQ, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SubGapEq(x uint64, y uint64) uint64
TEXT ·SubGapEq(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	SUBS R1, R0, R0
	MOVD $0x0000000000000000, R0
	BEQ  SubGapEq_yes
	JMP  SubGapEq_end

SubGapEq_yes:
	MOVD $0x0000000000000001, R0

SubGapEq_end:
	MOVD R0, ret+16(FP)
	RET

// func DecGapZero(x uint64, y uint64) uint64
TEXT ·DecGapZero(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	SUBS $1, R0, R0
	MOVD $0x0000000000000000, R0
	BEQ  DecGapZero_yes
	JMP  DecGapZero_end

DecGapZero_yes:
	MOVD $0x0000000000000001, R0

DecGapZero_end:
	MOVD R0, ret+16(FP)
	RET

// func CmpL32Eq(a uint64, b uint64) uint64
TEXT ·CmpL32Eq(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMPW R1, R0
	BEQ  CmpL32Eq_yes
	MOVD $0x0000000000000000, R0
	JMP  CmpL32Eq_end

CmpL32Eq_yes:
	MOVD $0x0000000000000001, R0

CmpL32Eq_end:
	MOVD R0, ret+16(FP)
	RET

// func CmpL32LessS(a uint64, b uint64) uint64
TEXT ·CmpL32LessS(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMPW R1, R0
	BLT  CmpL32LessS_yes
	MOVD $0x0000000000000000, R0
	JMP  CmpL32LessS_end

CmpL32LessS_yes:
	MOVD $0x0000000000000001, R0

CmpL32LessS_end:
	MOVD R0, ret+16(FP)
	RET

// func CmpL32LessU(a uint64, b uint64) uint64
TEXT ·CmpL32LessU(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	CMPW R1, R0
	BLO  CmpL32LessU_yes
	MOVD $0x0000000000000000, R0
	JMP  CmpL32LessU_end

CmpL32LessU_yes:
	MOVD $0x0000000000000001, R0

CmpL32LessU_end:
	MOVD R0, ret+16(FP)
	RET

// func TestL32(a uint64, m uint64) uint64
TEXT ·TestL32(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD m+8(FP), R1
	TSTW R1, R0
	BEQ  TestL32_zero
	MOVD $0x0000000000000000, R0
	JMP  TestL32_end

TestL32_zero:
	MOVD $0x0000000000000001, R0

TestL32_end:
	MOVD R0, ret+16(FP)
	RET

// func CmpW16Eq(a uint64, b uint64) uint64
TEXT ·CmpW16Eq(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	AND  $0xffff, R1, R16
	AND  $0xffff, R0, R15
	CMP  R16, R15
	BEQ  CmpW16Eq_yes
	MOVD $0x0000000000000000, R0
	JMP  CmpW16Eq_end

CmpW16Eq_yes:
	MOVD $0x0000000000000001, R0

CmpW16Eq_end:
	MOVD R0, ret+16(FP)
	RET

// func CmpB8Ne(a uint64, b uint64) uint64
TEXT ·CmpB8Ne(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	AND  $0xff, R1, R16
	AND  $0xff, R0, R15
	CMP  R16, R15
	BNE  CmpB8Ne_diff
	MOVD $0x0000000000000000, R0
	JMP  CmpB8Ne_end

CmpB8Ne_diff:
	MOVD $0x0000000000000001, R0

CmpB8Ne_end:
	MOVD R0, ret+16(FP)
	RET

// func TestW16Eq(a uint64, m uint64) uint64
TEXT ·TestW16Eq(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD m+8(FP), R1
	AND  $0xffff, R1, R16
	AND  $0xffff, R0, R15
	TST  R16, R15
	BEQ  TestW16Eq_zero
	MOVD $0x0000000000000000, R0
	JMP  TestW16Eq_end

TestW16Eq_zero:
	MOVD $0x0000000000000001, R0

TestW16Eq_end:
	MOVD R0, ret+16(FP)
	RET

// func IMul2(x uint64, y uint64) uint64
TEXT ·IMul2(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MUL  R0, R1, R1
	MOVD R1, ret+16(FP)
	RET

// func IMul3(x uint64) uint64
TEXT ·IMul3(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $-1640531535, R16
	MUL  R16, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func MulWide(x uint64, y uint64) (lo uint64, hi uint64)
TEXT ·MulWide(SB), NOSPLIT, $0-32
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R5
	UMULH R5, R0, R2
	MUL   R5, R0, R0
	MOVD  R0, lo+16(FP)
	MOVD  R2, hi+24(FP)
	RET

// func IMulWide(x int64, y int64) (lo uint64, hi uint64)
TEXT ·IMulWide(SB), NOSPLIT, $0-32
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R5
	SMULH R5, R0, R2
	MUL   R5, R0, R0
	MOVD  R0, lo+16(FP)
	MOVD  R2, hi+24(FP)
	RET

// func MulX(x uint64, y uint64) (lo uint64, hi uint64)
// Requires: BMI2
TEXT ·MulX(SB), NOSPLIT, $0-32
	MOVD  x+0(FP), R5
	MOVD  y+8(FP), R2
	MUL   R5, R2, R16
	UMULH R5, R2, R3
	MOVD  R16, R0
	MOVD  R0, lo+16(FP)
	MOVD  R3, hi+24(FP)
	RET

// func ShlX(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·ShlX(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	LSL  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func ShrX(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·ShrX(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	LSR  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func SarX(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·SarX(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	ASR  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func RorX(x uint64) uint64
// Requires: BMI2
TEXT ·RorX(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	ROR  $56, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func Bzhi(x uint64, n uint64) uint64
// Requires: BMI2
TEXT ·Bzhi(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD n+8(FP), R1
	MOVD $1, R16
	LSL  R1, R16, R16
	SUB  $1, R16, R16
	AND  R16, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Bextr88(x uint64) uint64
// Requires: BMI
TEXT ·Bextr88(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000808, R1
	UBFX $8, R0, $8, R0
	MOVD R0, ret+8(FP)
	RET

// func Bextr4_12(x uint64) uint64
// Requires: BMI
TEXT ·Bextr4_12(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000c04, R1
	UBFX $4, R0, $12, R0
	MOVD R0, ret+8(FP)
	RET

// func Bextr56_8(x uint64) uint64
// Requires: BMI
TEXT ·Bextr56_8(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000838, R1
	LSR  $56, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func Bextr8_56(x uint64) uint64
// Requires: BMI
TEXT ·Bextr8_56(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00003808, R1
	LSR  $8, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func Bextr8_60(x uint64) uint64
// Requires: BMI
TEXT ·Bextr8_60(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00003c08, R1
	LSR  $8, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func Bextr0_0(x uint64) uint64
// Requires: BMI
TEXT ·Bextr0_0(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000000, R1
	MOVD $0, R0
	MOVD R0, ret+8(FP)
	RET

// func Bextr70_8(x uint64) uint64
// Requires: BMI
TEXT ·Bextr70_8(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000846, R1
	MOVD $0, R0
	MOVD R0, ret+8(FP)
	RET

// func BzhiConst13(x uint64) uint64
// Requires: BMI2
TEXT ·BzhiConst13(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x0000000d, R1
	AND  $8191, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func BzhiConst0(x uint64) uint64
// Requires: BMI2
TEXT ·BzhiConst0(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000000, R1
	MOVD $0, R0
	MOVD R0, ret+8(FP)
	RET

// func BzhiConst64(x uint64) uint64
// Requires: BMI2
TEXT ·BzhiConst64(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000040, R1
	MOVD R0, ret+8(FP)
	RET

// func ShlXConst9(x uint64) uint64
// Requires: BMI2
TEXT ·ShlXConst9(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000009, R1
	LSL  $9, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func ShrXConst9(x uint64) uint64
// Requires: BMI2
TEXT ·ShrXConst9(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x00000009, R1
	LSR  $9, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func SetGe(a uint64, b uint64) uint64
TEXT ·SetGe(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD $0, R2
	CMP  R1, R0
	CSET GE, R16
	BFI  $0, R16, $8, R2
	MOVD R2, ret+16(FP)
	RET

// func AdcAccum(x uint64, acc uint64) uint64
TEXT ·AdcAccum(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  acc+8(FP), R1
	CMP   $0x04, R0
	CSINC HS, R1, R1, R16
	BFI   $0, R16, $8, R1
	MOVD  R1, ret+16(FP)
	RET

// func BswapL(x uint64) uint64
TEXT ·BswapL(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	REVW R0, R0
	MOVD R0, ret+8(FP)
	RET

// func AddByte(x uint64, y uint64) uint64
TEXT ·AddByte(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ADD  R0, R1, R15
	BFI  $0, R15, $8, R1
	MOVD R1, ret+16(FP)
	RET

// func MovbHighDst(x uint64, y uint64) uint64
TEXT ·MovbHighDst(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R1
	MOVD y+8(FP), R0
	BFI  $8, R1, $8, R0
	MOVD R0, ret+16(FP)
	RET

// func MovbLowPreserve(x uint64, y uint64) uint64
TEXT ·MovbLowPreserve(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R1
	MOVD y+8(FP), R0
	UBFX $8, R1, $8, R16
	BFI  $0, R16, $8, R0
	MOVD R0, ret+16(FP)
	RET

// func SelLtS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelLtS(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL LT, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelLeS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelLeS(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL LE, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelGtS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelGtS(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL GT, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelGeS(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelGeS(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL GE, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelLsU(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelLsU(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL LS, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelMi(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelMi(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL MI, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SelPl(a uint64, b uint64, c uint64, d uint64) uint64
// Requires: CMOV
TEXT ·SelPl(SB), NOSPLIT, $0-40
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD d+24(FP), R3
	CMP  R1, R0
	CSEL PL, R2, R3, R3
	MOVD R3, ret+32(FP)
	RET

// func SxL(x uint64) uint64
TEXT ·SxL(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVW R0, R0
	MOVD R0, ret+8(FP)
	RET

// func SxB(x uint64) uint64
TEXT ·SxB(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVB R0, R0
	MOVD R0, ret+8(FP)
	RET

// func SxBL(x uint64) uint64
TEXT ·SxBL(SB), NOSPLIT, $0-16
	MOVD  x+0(FP), R0
	MOVB  R0, R0
	MOVWU R0, R0
	MOVD  R0, ret+8(FP)
	RET

// func SxWL(x uint64) uint64
TEXT ·SxWL(SB), NOSPLIT, $0-16
	MOVD  x+0(FP), R0
	MOVH  R0, R0
	MOVWU R0, R0
	MOVD  R0, ret+8(FP)
	RET

// func NegL(x uint64) uint64
TEXT ·NegL(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	NEGW R0, R0
	MOVD R0, ret+8(FP)
	RET

// func NotL(x uint64) uint64
TEXT ·NotL(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MVNW R0, R0
	MOVD R0, ret+8(FP)
	RET

// func NotQ(x uint64) uint64
TEXT ·NotQ(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MVN  R0, R0
	MOVD R0, ret+8(FP)
	RET

// func RolL7(x uint64) uint64
TEXT ·RolL7(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	RORW $25, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func RorQ9(x uint64) uint64
TEXT ·RorQ9(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	ROR  $0x09, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func RorL9(x uint64) uint64
TEXT ·RorL9(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	RORW $0x09, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func BtrQ5(x uint64) uint64
TEXT ·BtrQ5(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x0000000000000005, R1
	MOVD $1, R16
	LSL  R1, R16, R16
	BIC  R16, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func BtcQ5(x uint64) uint64
TEXT ·BtcQ5(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD $0x0000000000000005, R1
	MOVD $1, R16
	LSL  R1, R16, R16
	EOR  R16, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func PopcntQ(x uint64) uint64
// Requires: POPCNT
TEXT ·PopcntQ(SB), NOSPLIT, $0-16
	MOVD    x+0(FP), R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	MOVD    R0, ret+8(FP)
	RET

// func SarQ3(x uint64) uint64
TEXT ·SarQ3(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	ASR  $0x03, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func SarL3(x uint64) uint64
TEXT ·SarL3(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	ASRW $0x03, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func IncL(x uint64) uint64
TEXT ·IncL(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	ADDW $1, R0, R0
	MOVD R0, ret+8(FP)
	RET

// func ShlB2(x uint64) uint64
TEXT ·ShlB2(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	LSLW $0x02, R0, R16
	BFI  $0, R16, $8, R0
	MOVD R0, ret+8(FP)
	RET

// func BsfQ(x uint64) uint64
TEXT ·BsfQ(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	RBIT R0, R1
	CLZ  R1, R1
	MOVD R1, ret+8(FP)
	RET

// func TzcntQ(x uint64) uint64
// Requires: BMI
TEXT ·TzcntQ(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	RBIT R0, R0
	CLZ  R0, R0
	MOVD R0, ret+8(FP)
	RET

// func AddL(x uint64, y uint64) uint64
TEXT ·AddL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ADDW R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func SubL(x uint64, y uint64) uint64
TEXT ·SubL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	SUBW R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func AndL(x uint64, y uint64) uint64
TEXT ·AndL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ANDW R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func OrL(x uint64, y uint64) uint64
TEXT ·OrL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ORRW R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func ImulL(x uint64, y uint64) uint64
TEXT ·ImulL(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MULW R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func XchgQ(x uint64, y uint64) uint64
TEXT ·XchgQ(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MOVD R1, R1
	MOVD R0, R16
	MOVD R1, R0
	MOVD R16, R1
	MOVD R0, ret+16(FP)
	RET

// func LeaL(x uint64, y uint64) uint64
TEXT ·LeaL(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	ADD   R1<<2, R0, R0
	ADD   $7, R0, R0
	MOVWU R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func VecZero(dst *[16]byte)
// Requires: SSE2
TEXT ·VecZero(SB), NOSPLIT, $0-8
	MOVD  dst+0(FP), R0
	VEOR  V0.B16, V0.B16, V0.B16
	FMOVQ F0, (R0)
	RET

// func VecCopyIdx(dst *[32]byte, src *[32]byte, i uint64)
// Requires: SSE2
TEXT ·VecCopyIdx(SB), NOSPLIT, $0-24
	MOVD  dst+0(FP), R0
	MOVD  src+8(FP), R1
	MOVD  i+16(FP), R2
	ADD   R2, R1, R15
	FMOVQ (R15), F0
	ADD   R2, R0, R15
	FMOVQ F0, (R15)
	RET

// func VecCopy(dst *[32]byte, src *[32]byte)
// Requires: SSE2
TEXT ·VecCopy(SB), NOSPLIT, $0-16
	MOVD  dst+0(FP), R0
	MOVD  src+8(FP), R1
	FMOVQ 16(R1), F0
	FMOVQ F0, 16(R0)
	RET

// func Prop0(x uint64, y uint64) uint64
TEXT ·Prop0(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	ASR   $0x05, R0, R0
	RORW  $27, R0, R0
	ANDW  R1, R0, R0
	MOVD  $0, R0
	ASR   $0x05, R0, R0
	LSLW  $0x02, R0, R16
	BFI   $0, R16, $8, R0
	MOVD  $0, R0
	NEG   R0, R0
	ORR   R1, R0, R0
	MOVHU R0, R0
	AND   R1, R0, R0
	MOVWU R1, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop1(x uint64, y uint64) uint64
// Requires: CMOV, POPCNT
TEXT ·Prop1(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	MOVD    $0, R0
	ROR     $51, R0, R0
	CMP     R1, R0
	CSEL    EQ, R1, R0, R0
	EOR     R1, R0, R0
	CMP     R1, R0
	CSEL    LO, R1, R0, R0
	CMP     R1, R0
	CSEL    LO, R1, R0, R0
	MVN     R0, R0
	ROR     $51, R0, R0
	MOVW    R0, R0
	AND     R1, R0, R0
	CMP     R1, R0
	CSEL    LO, R1, R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop2(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop2(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	CMP   R1, R0
	CSEL  EQ, R1, R0, R0
	NEG   R0, R0
	ADDW  R1, R0, R0
	MOVWU R1, R0
	MOVHU R0, R0
	ROR   $51, R0, R0
	SUBW  R1, R0, R0
	MUL   R1, R0, R0
	BFI   $0, R1, $8, R0
	REVW  R0, R0
	CMP   R1, R0
	CSEL  LO, R1, R0, R0
	ADD   R1, R0, R15
	BFI   $0, R15, $8, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop3(x uint64, y uint64) uint64
// Requires: BMI, CMOV
TEXT ·Prop3(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	MOVW  R0, R0
	SUB   R1, R0, R0
	CMP   R1, R0
	CSET  LT, R16
	BFI   $0, R16, $8, R0
	BFI   $0, R1, $8, R0
	CMP   R1, R0
	CSEL  EQ, R1, R0, R0
	CMP   R1, R0
	CSEL  LO, R1, R0, R0
	CMP   R1, R0
	CSEL  LO, R1, R0, R0
	LSL   $0x03, R0, R0
	ADD   R1, R0, R15
	BFI   $0, R15, $8, R0
	MOVHU R0, R0
	RBIT  R0, R0
	CLZ   R0, R0
	MULW  R1, R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop4(x uint64, y uint64) uint64
// Requires: BMI
TEXT ·Prop4(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	RORW  $27, R0, R0
	RORW  $27, R0, R0
	MUL   R1, R0, R0
	ADD   R1, R0, R0
	MOVHU R0, R0
	MOVD  $0, R0
	MVN   R0, R0
	LSL   $0x03, R0, R0
	ADD   R1, R0, R0
	LSR   $0x07, R0, R0
	RBIT  R0, R0
	CLZ   R0, R0
	ADD   R1, R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop5(x uint64, y uint64) uint64
// Requires: BMI, CMOV
TEXT ·Prop5(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ANDW R1, R0, R0
	LSR  $0x07, R0, R0
	LSLW $0x09, R0, R0
	LSLW $0x09, R0, R0
	MOVD $0, R0
	MULW R1, R0, R0
	CMP  R1, R0
	CSEL LO, R1, R0, R0
	SUBW R1, R0, R0
	RBIT R0, R0
	CLZ  R0, R0
	LSLW $0x09, R0, R0
	ROR  $51, R0, R0
	BFI  $0, R1, $8, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop6(x uint64, y uint64) uint64
// Requires: BMI, CMOV
TEXT ·Prop6(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	MOVWU R1, R0
	LSLW  $0x02, R0, R16
	BFI   $0, R16, $8, R0
	CMP   R1, R0
	CSEL  EQ, R1, R0, R0
	RBIT  R0, R0
	CLZ   R0, R0
	ORR   R1, R0, R0
	CMP   R1, R0
	CSEL  LO, R1, R0, R0
	MULW  R1, R0, R0
	MOVW  R0, R0
	CMP   R1, R0
	CSEL  EQ, R1, R0, R0
	ASR   $0x05, R0, R0
	LSR   $0x07, R0, R0
	MOVW  R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop7(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop7(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	LSLW $0x09, R0, R0
	AND  R1, R0, R0
	MULW R1, R0, R0
	ADDW R1, R0, R0
	ADD  R1, R0, R0
	SUBW R1, R0, R0
	CMP  R1, R0
	CSEL EQ, R1, R0, R0
	NEG  R0, R0
	ROR  $51, R0, R0
	ADD  R1, R0, R0
	RORW $27, R0, R0
	MOVW R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop8(x uint64, y uint64) uint64
// Requires: POPCNT
TEXT ·Prop8(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	ADDW    R1, R0, R0
	RORW    $27, R0, R0
	ADDW    R1, R0, R0
	NEG     R0, R0
	BFI     $0, R1, $8, R0
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	LSLW    $0x09, R0, R0
	MUL     R1, R0, R0
	AND     R1, R0, R0
	MOVD    $0, R0
	CMP     R1, R0
	CSET    LT, R16
	BFI     $0, R16, $8, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop9(x uint64, y uint64) uint64
// Requires: POPCNT
TEXT ·Prop9(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	ADDW    R1, R0, R0
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	MULW    R1, R0, R0
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	RORW    $27, R0, R0
	SUB     R1, R0, R0
	NEG     R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	ADDW    R1, R0, R0
	MULW    R1, R0, R0
	LSLW    $0x02, R0, R16
	BFI     $0, R16, $8, R0
	MVN     R0, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop10(x uint64, y uint64) uint64
// Requires: BMI, POPCNT
TEXT ·Prop10(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	MUL     R1, R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	ADDW    R1, R0, R0
	RBIT    R0, R0
	CLZ     R0, R0
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	ROR     $51, R0, R0
	SUBW    R1, R0, R0
	MUL     R1, R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	MUL     R1, R0, R0
	MVN     R0, R0
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop11(x uint64, y uint64) uint64
// Requires: CMOV, POPCNT
TEXT ·Prop11(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	ANDW    R1, R0, R0
	MVN     R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	RORW    $27, R0, R0
	ADDW    R1, R0, R0
	RORW    $27, R0, R0
	CMP     R1, R0
	CSEL    LO, R1, R0, R0
	CMP     R1, R0
	CSET    LT, R16
	BFI     $0, R16, $8, R0
	ASR     $0x05, R0, R0
	BFI     $0, R1, $8, R0
	MULW    R1, R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop12(x uint64, y uint64) uint64
// Requires: BMI, CMOV, POPCNT
TEXT ·Prop12(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	SUB     R1, R0, R0
	CMP     R1, R0
	CSEL    LO, R1, R0, R0
	CMP     R1, R0
	CSEL    LO, R1, R0, R0
	RBIT    R0, R0
	CLZ     R0, R0
	MVN     R0, R0
	SUB     R1, R0, R0
	EOR     R1, R0, R0
	ADD     R1, R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	MOVW    R0, R0
	MUL     R1, R0, R0
	LSLW    $0x02, R0, R16
	BFI     $0, R16, $8, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop13(x uint64, y uint64) uint64
TEXT ·Prop13(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	AND   R1, R0, R0
	CMP   R1, R0
	CSET  LT, R16
	BFI   $0, R16, $8, R0
	MUL   R1, R0, R0
	ADD   R1, R0, R0
	MOVD  $0, R0
	AND   R1, R0, R0
	MOVHU R0, R0
	SUBW  R1, R0, R0
	ORR   R1, R0, R0
	LSL   $0x03, R0, R0
	AND   R1, R0, R0
	MOVWU R1, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop14(x uint64, y uint64) uint64
// Requires: POPCNT
TEXT ·Prop14(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	SUBW    R1, R0, R0
	LSR     $0x07, R0, R0
	ADDW    R1, R0, R0
	MOVHU   R0, R0
	ROR     $51, R0, R0
	LSL     $0x03, R0, R0
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	NEG     R0, R0
	EOR     R1, R0, R0
	SUB     R1, R0, R0
	CMP     R1, R0
	CSET    LT, R16
	BFI     $0, R16, $8, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop15(x uint64, y uint64) uint64
// Requires: CMOV, POPCNT
TEXT ·Prop15(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	ROR     $51, R0, R0
	LSL     $0x03, R0, R0
	MVN     R0, R0
	AND     R1, R0, R0
	MOVHU   R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	RORW    $27, R0, R0
	LSL     $0x03, R0, R0
	SUBW    R1, R0, R0
	CMP     R1, R0
	CSEL    LO, R1, R0, R0
	MUL     R1, R0, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop16(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop16(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	SUB   R1, R0, R0
	ANDW  R1, R0, R0
	REVW  R0, R0
	RORW  $27, R0, R0
	MOVHU R0, R0
	AND   R1, R0, R0
	RORW  $27, R0, R0
	LSLW  $0x09, R0, R0
	LSLW  $0x09, R0, R0
	CMP   R1, R0
	CSEL  LO, R1, R0, R0
	ADD   R1, R0, R0
	ANDW  R1, R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop17(x uint64, y uint64) uint64
TEXT ·Prop17(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	ORR   R1, R0, R0
	MOVHU R0, R0
	ANDW  R1, R0, R0
	SUBW  R1, R0, R0
	ROR   $51, R0, R0
	ORR   R1, R0, R0
	REVW  R0, R0
	LSR   $0x07, R0, R0
	LSR   $0x07, R0, R0
	MOVD  $0, R0
	LSR   $0x07, R0, R0
	MVN   R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop18(x uint64, y uint64) uint64
// Requires: BMI
TEXT ·Prop18(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	ORR   R1, R0, R0
	MULW  R1, R0, R0
	LSR   $0x07, R0, R0
	MVN   R0, R0
	ROR   $51, R0, R0
	SUBW  R1, R0, R0
	MOVWU R1, R0
	EOR   R1, R0, R0
	MUL   R1, R0, R0
	SUBW  R1, R0, R0
	MOVWU R1, R0
	RBIT  R0, R0
	CLZ   R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop19(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop19(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ADD  R1, R0, R0
	LSL  $0x03, R0, R0
	LSLW $0x09, R0, R0
	RORW $27, R0, R0
	AND  R1, R0, R0
	ADDW R1, R0, R0
	RORW $27, R0, R0
	ROR  $51, R0, R0
	CMP  R1, R0
	CSEL LO, R1, R0, R0
	ADDW R1, R0, R0
	LSLW $0x09, R0, R0
	MOVD $0, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop20(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop20(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	RORW  $27, R0, R0
	CMP   R1, R0
	CSEL  EQ, R1, R0, R0
	ADD   R1, R0, R0
	MOVHU R0, R0
	SUB   R1, R0, R0
	NEG   R0, R0
	CMP   R1, R0
	CSEL  LO, R1, R0, R0
	ASR   $0x05, R0, R0
	ADDW  R1, R0, R0
	MUL   R1, R0, R0
	LSR   $0x07, R0, R0
	SUBW  R1, R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop21(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop21(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ASR  $0x05, R0, R0
	LSLW $0x09, R0, R0
	REVW R0, R0
	MOVW R0, R0
	SUBW R1, R0, R0
	ASR  $0x05, R0, R0
	CMP  R1, R0
	CSEL LO, R1, R0, R0
	ASR  $0x05, R0, R0
	SUB  R1, R0, R0
	LSLW $0x09, R0, R0
	CMP  R1, R0
	CSET LT, R16
	BFI  $0, R16, $8, R0
	MUL  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop22(x uint64, y uint64) uint64
TEXT ·Prop22(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	AND  R1, R0, R0
	LSLW $0x02, R0, R16
	BFI  $0, R16, $8, R0
	AND  R1, R0, R0
	ASR  $0x05, R0, R0
	MUL  R1, R0, R0
	BFI  $0, R1, $8, R0
	LSLW $0x09, R0, R0
	AND  R1, R0, R0
	ASR  $0x05, R0, R0
	ANDW R1, R0, R0
	ORR  R1, R0, R0
	ADDW R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop23(x uint64, y uint64) uint64
TEXT ·Prop23(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	ANDW  R1, R0, R0
	MOVWU R1, R0
	ROR   $51, R0, R0
	ORR   R1, R0, R0
	MUL   R1, R0, R0
	MVN   R0, R0
	MOVW  R0, R0
	LSR   $0x07, R0, R0
	LSLW  $0x02, R0, R16
	BFI   $0, R16, $8, R0
	LSLW  $0x02, R0, R16
	BFI   $0, R16, $8, R0
	AND   R1, R0, R0
	LSL   $0x03, R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop24(x uint64, y uint64) uint64
// Requires: POPCNT
TEXT ·Prop24(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	MULW    R1, R0, R0
	ROR     $51, R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	REVW    R0, R0
	SUBW    R1, R0, R0
	MOVHU   R0, R0
	ADD     R1, R0, R0
	MOVWU   R1, R0
	ASR     $0x05, R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	NEG     R0, R0
	MOVWU   R1, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop25(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop25(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	CMP  R1, R0
	CSET LT, R16
	BFI  $0, R16, $8, R0
	CMP  R1, R0
	CSEL LO, R1, R0, R0
	ADD  R1, R0, R15
	BFI  $0, R15, $8, R0
	LSLW $0x09, R0, R0
	BFI  $0, R1, $8, R0
	ROR  $51, R0, R0
	AND  R1, R0, R0
	REVW R0, R0
	MVN  R0, R0
	MOVD $0, R0
	LSLW $0x02, R0, R16
	BFI  $0, R16, $8, R0
	REVW R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop26(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop26(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	CMP  R1, R0
	CSEL LO, R1, R0, R0
	MVN  R0, R0
	CMP  R1, R0
	CSET LT, R16
	BFI  $0, R16, $8, R0
	BFI  $0, R1, $8, R0
	MOVW R0, R0
	REVW R0, R0
	CMP  R1, R0
	CSEL EQ, R1, R0, R0
	MOVW R0, R0
	BFI  $0, R1, $8, R0
	LSL  $0x03, R0, R0
	LSL  $0x03, R0, R0
	ANDW R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop27(x uint64, y uint64) uint64
// Requires: BMI, POPCNT
TEXT ·Prop27(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	RBIT    R0, R0
	CLZ     R0, R0
	ADD     R1, R0, R0
	RBIT    R0, R0
	CLZ     R0, R0
	MOVD    $0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	SUB     R1, R0, R0
	ROR     $51, R0, R0
	MULW    R1, R0, R0
	MUL     R1, R0, R0
	ROR     $51, R0, R0
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop28(x uint64, y uint64) uint64
TEXT ·Prop28(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	MOVHU R0, R0
	ROR   $51, R0, R0
	ORR   R1, R0, R0
	ASR   $0x05, R0, R0
	EOR   R1, R0, R0
	AND   R1, R0, R0
	MUL   R1, R0, R0
	ADD   R1, R0, R15
	BFI   $0, R15, $8, R0
	MOVD  $0, R0
	NEG   R0, R0
	MVN   R0, R0
	SUB   R1, R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop29(x uint64, y uint64) uint64
// Requires: POPCNT
TEXT ·Prop29(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	RORW    $27, R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	ANDW    R1, R0, R0
	LSLW    $0x09, R0, R0
	MOVD    $0, R0
	ASR     $0x05, R0, R0
	EOR     R1, R0, R0
	NEG     R0, R0
	LSLW    $0x09, R0, R0
	LSR     $0x07, R0, R0
	BFI     $0, R1, $8, R0
	LSLW    $0x02, R0, R16
	BFI     $0, R16, $8, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop30(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop30(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	LSLW $0x09, R0, R0
	CMP  R1, R0
	CSEL LO, R1, R0, R0
	RORW $27, R0, R0
	ROR  $51, R0, R0
	CMP  R1, R0
	CSEL LO, R1, R0, R0
	ANDW R1, R0, R0
	MUL  R1, R0, R0
	LSLW $0x02, R0, R16
	BFI  $0, R16, $8, R0
	ORR  R1, R0, R0
	RORW $27, R0, R0
	LSL  $0x03, R0, R0
	ANDW R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop31(x uint64, y uint64) uint64
// Requires: BMI
TEXT ·Prop31(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	ORR   R1, R0, R0
	LSLW  $0x02, R0, R16
	BFI   $0, R16, $8, R0
	EOR   R1, R0, R0
	LSR   $0x07, R0, R0
	ROR   $51, R0, R0
	ADD   R1, R0, R15
	BFI   $0, R15, $8, R0
	ORR   R1, R0, R0
	RORW  $27, R0, R0
	ASR   $0x05, R0, R0
	RBIT  R0, R0
	CLZ   R0, R0
	ORR   R1, R0, R0
	MOVHU R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop32(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop32(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	MULW  R1, R0, R0
	LSLW  $0x02, R0, R16
	BFI   $0, R16, $8, R0
	MVN   R0, R0
	ANDW  R1, R0, R0
	NEG   R0, R0
	MOVHU R0, R0
	BFI   $0, R1, $8, R0
	CMP   R1, R0
	CSEL  LO, R1, R0, R0
	ADDW  R1, R0, R0
	LSLW  $0x02, R0, R16
	BFI   $0, R16, $8, R0
	ROR   $51, R0, R0
	MOVHU R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop33(x uint64, y uint64) uint64
TEXT ·Prop33(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	MUL   R1, R0, R0
	LSL   $0x03, R0, R0
	BFI   $0, R1, $8, R0
	MOVW  R0, R0
	LSR   $0x07, R0, R0
	LSR   $0x07, R0, R0
	ROR   $51, R0, R0
	LSR   $0x07, R0, R0
	ADDW  R1, R0, R0
	MOVWU R1, R0
	RORW  $27, R0, R0
	LSLW  $0x09, R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop34(x uint64, y uint64) uint64
// Requires: BMI
TEXT ·Prop34(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	ORR   R1, R0, R0
	ASR   $0x05, R0, R0
	MOVWU R1, R0
	ADD   R1, R0, R0
	REVW  R0, R0
	ADD   R1, R0, R15
	BFI   $0, R15, $8, R0
	REVW  R0, R0
	LSLW  $0x02, R0, R16
	BFI   $0, R16, $8, R0
	MOVWU R1, R0
	RBIT  R0, R0
	CLZ   R0, R0
	ANDW  R1, R0, R0
	SUBW  R1, R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop35(x uint64, y uint64) uint64
// Requires: POPCNT
TEXT ·Prop35(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	ORR     R1, R0, R0
	ADD     R1, R0, R0
	MOVWU   R1, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	MOVHU   R0, R0
	ROR     $51, R0, R0
	LSL     $0x03, R0, R0
	EOR     R1, R0, R0
	LSR     $0x07, R0, R0
	SUB     R1, R0, R0
	LSLW    $0x02, R0, R16
	BFI     $0, R16, $8, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop36(x uint64, y uint64) uint64
// Requires: BMI, CMOV
TEXT ·Prop36(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	SUBW  R1, R0, R0
	CMP   R1, R0
	CSEL  EQ, R1, R0, R0
	RORW  $27, R0, R0
	MOVHU R0, R0
	MVN   R0, R0
	RBIT  R0, R0
	CLZ   R0, R0
	ASR   $0x05, R0, R0
	ROR   $51, R0, R0
	MVN   R0, R0
	LSLW  $0x09, R0, R0
	RBIT  R0, R0
	CLZ   R0, R0
	MOVWU R1, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop37(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop37(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	LSR   $0x07, R0, R0
	MULW  R1, R0, R0
	ADD   R1, R0, R0
	CMP   R1, R0
	CSEL  LO, R1, R0, R0
	SUBW  R1, R0, R0
	ADDW  R1, R0, R0
	MOVWU R1, R0
	ADD   R1, R0, R15
	BFI   $0, R15, $8, R0
	AND   R1, R0, R0
	LSL   $0x03, R0, R0
	ASR   $0x05, R0, R0
	LSLW  $0x09, R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop38(x uint64, y uint64) uint64
// Requires: POPCNT
TEXT ·Prop38(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	MULW    R1, R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	BFI     $0, R1, $8, R0
	SUBW    R1, R0, R0
	BFI     $0, R1, $8, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	LSR     $0x07, R0, R0
	BFI     $0, R1, $8, R0
	ORR     R1, R0, R0
	ANDW    R1, R0, R0
	LSLW    $0x09, R0, R0
	REVW    R0, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop39(x uint64, y uint64) uint64
// Requires: BMI
TEXT ·Prop39(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	ADDW  R1, R0, R0
	MOVHU R0, R0
	RBIT  R0, R0
	CLZ   R0, R0
	NEG   R0, R0
	REVW  R0, R0
	ASR   $0x05, R0, R0
	MUL   R1, R0, R0
	AND   R1, R0, R0
	RBIT  R0, R0
	CLZ   R0, R0
	ANDW  R1, R0, R0
	MOVHU R0, R0
	ASR   $0x05, R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop40(x uint64, y uint64) uint64
TEXT ·Prop40(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	ADD   R1, R0, R0
	MOVHU R0, R0
	BFI   $0, R1, $8, R0
	MUL   R1, R0, R0
	ADD   R1, R0, R15
	BFI   $0, R15, $8, R0
	MUL   R1, R0, R0
	CMP   R1, R0
	CSET  LT, R16
	BFI   $0, R16, $8, R0
	EOR   R1, R0, R0
	NEG   R0, R0
	MVN   R0, R0
	SUB   R1, R0, R0
	AND   R1, R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop41(x uint64, y uint64) uint64
// Requires: BMI, POPCNT
TEXT ·Prop41(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	ASR     $0x05, R0, R0
	LSL     $0x03, R0, R0
	MOVD    $0, R0
	REVW    R0, R0
	LSLW    $0x02, R0, R16
	BFI     $0, R16, $8, R0
	MOVHU   R0, R0
	MOVHU   R0, R0
	RBIT    R0, R0
	CLZ     R0, R0
	NEG     R0, R0
	MVN     R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	LSLW    $0x02, R0, R16
	BFI     $0, R16, $8, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop42(x uint64, y uint64) uint64
TEXT ·Prop42(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	LSLW  $0x02, R0, R16
	BFI   $0, R16, $8, R0
	LSLW  $0x09, R0, R0
	MOVWU R1, R0
	MOVW  R0, R0
	RORW  $27, R0, R0
	ORR   R1, R0, R0
	EOR   R1, R0, R0
	ASR   $0x05, R0, R0
	ASR   $0x05, R0, R0
	RORW  $27, R0, R0
	EOR   R1, R0, R0
	ADD   R1, R0, R15
	BFI   $0, R15, $8, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop43(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop43(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MOVW R0, R0
	ANDW R1, R0, R0
	CMP  R1, R0
	CSEL EQ, R1, R0, R0
	CMP  R1, R0
	CSET LT, R16
	BFI  $0, R16, $8, R0
	ADD  R1, R0, R15
	BFI  $0, R15, $8, R0
	LSLW $0x09, R0, R0
	CMP  R1, R0
	CSEL LO, R1, R0, R0
	ADDW R1, R0, R0
	MOVD $0, R0
	LSL  $0x03, R0, R0
	CMP  R1, R0
	CSET LT, R16
	BFI  $0, R16, $8, R0
	MOVD $0, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop44(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop44(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	CMP  R1, R0
	CSEL LO, R1, R0, R0
	AND  R1, R0, R0
	ADDW R1, R0, R0
	CMP  R1, R0
	CSET LT, R16
	BFI  $0, R16, $8, R0
	ADD  R1, R0, R15
	BFI  $0, R15, $8, R0
	BFI  $0, R1, $8, R0
	AND  R1, R0, R0
	MUL  R1, R0, R0
	LSLW $0x09, R0, R0
	ADD  R1, R0, R0
	EOR  R1, R0, R0
	SUB  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop45(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop45(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	SUBW R1, R0, R0
	NEG  R0, R0
	CMP  R1, R0
	CSET LT, R16
	BFI  $0, R16, $8, R0
	ADD  R1, R0, R0
	ADD  R1, R0, R15
	BFI  $0, R15, $8, R0
	ROR  $51, R0, R0
	ADDW R1, R0, R0
	CMP  R1, R0
	CSEL EQ, R1, R0, R0
	CMP  R1, R0
	CSEL LO, R1, R0, R0
	ASR  $0x05, R0, R0
	MOVD $0, R0
	ASR  $0x05, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop46(x uint64, y uint64) uint64
TEXT ·Prop46(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	NEG  R0, R0
	ANDW R1, R0, R0
	MOVD $0, R0
	MOVW R0, R0
	MULW R1, R0, R0
	NEG  R0, R0
	MULW R1, R0, R0
	ADDW R1, R0, R0
	NEG  R0, R0
	REVW R0, R0
	LSLW $0x02, R0, R16
	BFI  $0, R16, $8, R0
	BFI  $0, R1, $8, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop47(x uint64, y uint64) uint64
TEXT ·Prop47(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MVN  R0, R0
	ADD  R1, R0, R15
	BFI  $0, R15, $8, R0
	ASR  $0x05, R0, R0
	AND  R1, R0, R0
	MUL  R1, R0, R0
	NEG  R0, R0
	RORW $27, R0, R0
	LSR  $0x07, R0, R0
	MUL  R1, R0, R0
	EOR  R1, R0, R0
	ADDW R1, R0, R0
	ASR  $0x05, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop48(x uint64, y uint64) uint64
// Requires: CMOV, POPCNT
TEXT ·Prop48(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	MUL     R1, R0, R0
	LSL     $0x03, R0, R0
	ADDW    R1, R0, R0
	EOR     R1, R0, R0
	NEG     R0, R0
	CMP     R1, R0
	CSEL    EQ, R1, R0, R0
	MUL     R1, R0, R0
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	ADDW    R1, R0, R0
	MOVW    R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	CMP     R1, R0
	CSEL    LO, R1, R0, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop49(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop49(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MOVW R0, R0
	LSLW $0x09, R0, R0
	MVN  R0, R0
	CMP  R1, R0
	CSET LT, R16
	BFI  $0, R16, $8, R0
	LSLW $0x02, R0, R16
	BFI  $0, R16, $8, R0
	ROR  $51, R0, R0
	ADD  R1, R0, R0
	CMP  R1, R0
	CSEL EQ, R1, R0, R0
	NEG  R0, R0
	LSR  $0x07, R0, R0
	CMP  R1, R0
	CSEL EQ, R1, R0, R0
	ANDW R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop50(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop50(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	ADDW  R1, R0, R0
	MOVHU R0, R0
	MOVWU R1, R0
	AND   R1, R0, R0
	SUBW  R1, R0, R0
	CMP   R1, R0
	CSEL  LO, R1, R0, R0
	CMP   R1, R0
	CSEL  EQ, R1, R0, R0
	MVN   R0, R0
	SUB   R1, R0, R0
	RORW  $27, R0, R0
	ADD   R1, R0, R0
	MUL   R1, R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop51(x uint64, y uint64) uint64
TEXT ·Prop51(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MULW R1, R0, R0
	NEG  R0, R0
	SUB  R1, R0, R0
	ASR  $0x05, R0, R0
	LSR  $0x07, R0, R0
	ORR  R1, R0, R0
	ASR  $0x05, R0, R0
	RORW $27, R0, R0
	MULW R1, R0, R0
	RORW $27, R0, R0
	ADD  R1, R0, R0
	SUB  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop52(x uint64, y uint64) uint64
// Requires: BMI, CMOV, POPCNT
TEXT ·Prop52(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	LSLW    $0x02, R0, R16
	BFI     $0, R16, $8, R0
	CMP     R1, R0
	CSET    LT, R16
	BFI     $0, R16, $8, R0
	REVW    R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	MVN     R0, R0
	RBIT    R0, R0
	CLZ     R0, R0
	CMP     R1, R0
	CSET    LT, R16
	BFI     $0, R16, $8, R0
	MUL     R1, R0, R0
	RORW    $27, R0, R0
	CMP     R1, R0
	CSEL    EQ, R1, R0, R0
	CMP     R1, R0
	CSEL    LO, R1, R0, R0
	ASR     $0x05, R0, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop53(x uint64, y uint64) uint64
// Requires: BMI
TEXT ·Prop53(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	ASR  $0x05, R0, R0
	MOVD $0, R0
	MULW R1, R0, R0
	LSR  $0x07, R0, R0
	SUBW R1, R0, R0
	RORW $27, R0, R0
	RBIT R0, R0
	CLZ  R0, R0
	ROR  $51, R0, R0
	BFI  $0, R1, $8, R0
	LSL  $0x03, R0, R0
	ASR  $0x05, R0, R0
	MUL  R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop54(x uint64, y uint64) uint64
// Requires: BMI, CMOV
TEXT ·Prop54(SB), NOSPLIT, $0-24
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	SUB  R1, R0, R0
	CMP  R1, R0
	CSET LT, R16
	BFI  $0, R16, $8, R0
	CMP  R1, R0
	CSEL LO, R1, R0, R0
	EOR  R1, R0, R0
	MOVD $0, R0
	BFI  $0, R1, $8, R0
	LSLW $0x09, R0, R0
	RBIT R0, R0
	CLZ  R0, R0
	CMP  R1, R0
	CSEL EQ, R1, R0, R0
	EOR  R1, R0, R0
	ROR  $51, R0, R0
	MULW R1, R0, R0
	MOVD R0, ret+16(FP)
	RET

// func Prop55(x uint64, y uint64) uint64
// Requires: CMOV
TEXT ·Prop55(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	CMP   R1, R0
	CSEL  EQ, R1, R0, R0
	ADD   R1, R0, R0
	MOVHU R0, R0
	CMP   R1, R0
	CSEL  LO, R1, R0, R0
	LSR   $0x07, R0, R0
	ROR   $51, R0, R0
	EOR   R1, R0, R0
	CMP   R1, R0
	CSEL  EQ, R1, R0, R0
	CMP   R1, R0
	CSEL  LO, R1, R0, R0
	LSLW  $0x02, R0, R16
	BFI   $0, R16, $8, R0
	LSL   $0x03, R0, R0
	NEG   R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop56(x uint64, y uint64) uint64
// Requires: BMI
TEXT ·Prop56(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	RBIT  R0, R0
	CLZ   R0, R0
	ASR   $0x05, R0, R0
	MVN   R0, R0
	LSL   $0x03, R0, R0
	ADD   R1, R0, R0
	ORR   R1, R0, R0
	MUL   R1, R0, R0
	MOVHU R0, R0
	REVW  R0, R0
	ADD   R1, R0, R15
	BFI   $0, R15, $8, R0
	ANDW  R1, R0, R0
	RORW  $27, R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop57(x uint64, y uint64) uint64
// Requires: BMI
TEXT ·Prop57(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	SUB   R1, R0, R0
	ORR   R1, R0, R0
	BFI   $0, R1, $8, R0
	LSLW  $0x02, R0, R16
	BFI   $0, R16, $8, R0
	MOVD  $0, R0
	LSL   $0x03, R0, R0
	ANDW  R1, R0, R0
	RBIT  R0, R0
	CLZ   R0, R0
	MOVHU R0, R0
	RBIT  R0, R0
	CLZ   R0, R0
	ADD   R1, R0, R0
	LSL   $0x03, R0, R0
	MOVD  R0, ret+16(FP)
	RET

// func Prop58(x uint64, y uint64) uint64
// Requires: CMOV, POPCNT
TEXT ·Prop58(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	MOVWU   R1, R0
	NEG     R0, R0
	CMP     R1, R0
	CSEL    EQ, R1, R0, R0
	MULW    R1, R0, R0
	MULW    R1, R0, R0
	MVN     R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	BFI     $0, R1, $8, R0
	NEG     R0, R0
	LSLW    $0x09, R0, R0
	NEG     R0, R0
	LSL     $0x03, R0, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop59(x uint64, y uint64) uint64
// Requires: CMOV, POPCNT
TEXT ·Prop59(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	ASR     $0x05, R0, R0
	ORR     R1, R0, R0
	ANDW    R1, R0, R0
	ANDW    R1, R0, R0
	MOVW    R0, R0
	LSL     $0x03, R0, R0
	AND     R1, R0, R0
	SUBW    R1, R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	MULW    R1, R0, R0
	CMP     R1, R0
	CSEL    LO, R1, R0, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop60(x uint64, y uint64) uint64
// Requires: POPCNT
TEXT ·Prop60(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	LSLW    $0x09, R0, R0
	ADDW    R1, R0, R0
	LSLW    $0x02, R0, R16
	BFI     $0, R16, $8, R0
	MOVW    R0, R0
	LSL     $0x03, R0, R0
	ASR     $0x05, R0, R0
	LSLW    $0x09, R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	BFI     $0, R1, $8, R0
	AND     R1, R0, R0
	LSL     $0x03, R0, R0
	ANDW    R1, R0, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop61(x uint64, y uint64) uint64
// Requires: CMOV, POPCNT
TEXT ·Prop61(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	MOVHU   R0, R0
	CMP     R1, R0
	CSET    LT, R16
	BFI     $0, R16, $8, R0
	LSLW    $0x09, R0, R0
	CMP     R1, R0
	CSEL    EQ, R1, R0, R0
	MUL     R1, R0, R0
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	BFI     $0, R1, $8, R0
	RORW    $27, R0, R0
	ADD     R1, R0, R0
	RORW    $27, R0, R0
	MOVW    R0, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop62(x uint64, y uint64) uint64
// Requires: POPCNT
TEXT ·Prop62(SB), NOSPLIT, $0-24
	MOVD    x+0(FP), R0
	MOVD    y+8(FP), R1
	SUBW    R1, R0, R0
	EOR     R1, R0, R0
	ASR     $0x05, R0, R0
	ADD     R1, R0, R15
	BFI     $0, R15, $8, R0
	ADD     R1, R0, R0
	FMOVD   R0, F31
	VCNT    V31.B8, V31.B8
	VUADDLV V31.B8, V31
	FMOVD   F31, R0
	EOR     R1, R0, R0
	ADDW    R1, R0, R0
	BFI     $0, R1, $8, R0
	MOVW    R0, R0
	LSR     $0x07, R0, R0
	AND     R1, R0, R0
	MOVD    R0, ret+16(FP)
	RET

// func Prop63(x uint64, y uint64) uint64
// Requires: BMI, CMOV
TEXT ·Prop63(SB), NOSPLIT, $0-24
	MOVD  x+0(FP), R0
	MOVD  y+8(FP), R1
	RBIT  R0, R0
	CLZ   R0, R0
	MOVWU R1, R0
	AND   R1, R0, R0
	RBIT  R0, R0
	CLZ   R0, R0
	ANDW  R1, R0, R0
	RBIT  R0, R0
	CLZ   R0, R0
	REVW  R0, R0
	CMP   R1, R0
	CSEL  LO, R1, R0, R0
	MULW  R1, R0, R0
	SUBW  R1, R0, R0
	MVN   R0, R0
	EOR   R1, R0, R0
	MOVD  R0, ret+16(FP)
	RET
