// Package arm64lower runs the functions generated by asm.go against pure-Go
// references. The generated asm is produced for both amd64 and arm64 from one
// avo source, so running this test on each architecture (CI does both) verifies
// the arm64 lowering printer is semantics-preserving.
package arm64lower

import (
	"math/bits"
	"testing"
	"testing/quick"
)

//go:generate go run asm.go -out lower_amd64.s -arm64 lower_arm64.s -stubs stub.go

func TestArith(t *testing.T) {
	cases := []struct {
		name string
		got  interface{}
		want interface{}
	}{
		{"Add", Add, func(x, y uint64) uint64 { return x + y }},
		{"Sub", Sub, func(x, y uint64) uint64 { return x - y }},
		{"Neg", Neg, func(x uint64) uint64 { return -x }},
		{"AndOrXor", AndOrXor, func(x, y uint64) uint64 { return (x & y) ^ (x | y) }},
		{"ShlCL", ShlCL, func(x, n uint64) uint64 { return x << (n & 63) }},
		{"ShrCL", ShrCL, func(x, n uint64) uint64 { return x >> (n & 63) }},
		{"RolCL", RolCL, func(x, n uint64) uint64 { return bits.RotateLeft64(x, int(n&63)) }},
		{"ZeroExt32", ZeroExt32, func(x uint64) uint64 { return uint64(uint32(x)) + x }},
		{"HighByte", HighByte, func(x uint64) uint64 { return (x >> 8) & 0xff }},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if err := quick.CheckEqual(c.got, c.want, nil); err != nil {
				t.Error(err)
			}
		})
	}
}

func TestConditions(t *testing.T) {
	b2u := func(b bool) uint64 {
		if b {
			return 1
		}
		return 0
	}
	pairs := []struct{ a, b uint64 }{
		{0, 0}, {1, 0}, {0, 1}, {5, 5}, {5, 6}, {6, 5},
		{^uint64(0), 0}, {0, ^uint64(0)}, // -1 vs 0 (signed) / max vs 0 (unsigned)
		{^uint64(0), 1}, {1, ^uint64(0)},
		{1 << 63, 1}, {1, 1 << 63}, // sign-bit boundaries
	}
	conds := []struct {
		name string
		got  func(a, b uint64) uint64
		want func(a, b uint64) bool
	}{
		{"LessS", LessS, func(a, b uint64) bool { return int64(a) < int64(b) }},
		{"GreaterEqS", GreaterEqS, func(a, b uint64) bool { return int64(a) >= int64(b) }},
		{"LessU", LessU, func(a, b uint64) bool { return a < b }},
		{"AboveU", AboveU, func(a, b uint64) bool { return a > b }},
		{"Equal", Equal, func(a, b uint64) bool { return a == b }},
	}
	for _, c := range conds {
		t.Run(c.name, func(t *testing.T) {
			for _, p := range pairs {
				if got, want := c.got(p.a, p.b), b2u(c.want(p.a, p.b)); got != want {
					t.Errorf("%s(%#x, %#x) = %d, want %d", c.name, p.a, p.b, got, want)
				}
			}
		})
	}
}

func TestSelectEq(t *testing.T) {
	ref := func(a, b, c, d uint64) uint64 {
		if a == b {
			return c
		}
		return d
	}
	cases := [][4]uint64{
		{1, 1, 7, 9}, {1, 2, 7, 9}, {0, 0, 100, 200}, {5, 6, 100, 200},
	}
	for _, c := range cases {
		if got, want := SelectEq(c[0], c[1], c[2], c[3]), ref(c[0], c[1], c[2], c[3]); got != want {
			t.Errorf("SelectEq%v = %d, want %d", c, got, want)
		}
	}
}

// TestFlagGap covers a flag-setting instruction separated from the conditional
// branch that consumes its result by a flag-transparent MOV. The lowering must
// still emit the flag-setting variant of the producer; otherwise the branch
// reads stale NZCV and the result is wrong for some inputs.
func TestFlagGap(t *testing.T) {
	b2u := func(b bool) uint64 {
		if b {
			return 1
		}
		return 0
	}
	t.Run("SubGapEq", func(t *testing.T) {
		for _, p := range []struct{ x, y uint64 }{{5, 5}, {5, 6}, {0, 0}, {1, 0}} {
			if got, want := SubGapEq(p.x, p.y), b2u(p.x == p.y); got != want {
				t.Errorf("SubGapEq(%d, %d) = %d, want %d", p.x, p.y, got, want)
			}
		}
	})
	t.Run("DecGapZero", func(t *testing.T) {
		for _, x := range []uint64{0, 1, 2, 100} {
			if got, want := DecGapZero(x, 0), b2u(x-1 == 0); got != want {
				t.Errorf("DecGapZero(%d) = %d, want %d", x, got, want)
			}
		}
	})
}

// TestCompareWidth covers 32-bit CMPL/TESTL on operands whose upper 32 bits
// differ. A correct lowering compares only the low 32 bits; folding to a 64-bit
// compare is observably wrong here, for signed and unsigned conditions alike.
func TestCompareWidth(t *testing.T) {
	b2u := func(b bool) uint64 {
		if b {
			return 1
		}
		return 0
	}
	t.Run("CmpL32Eq", func(t *testing.T) {
		pairs := []struct{ a, b uint64 }{
			{0x1_00000005, 0x2_00000005}, // low32 equal, high32 differ
			{0x1_00000005, 0x1_00000006}, // low32 differ
		}
		for _, p := range pairs {
			if got, want := CmpL32Eq(p.a, p.b), b2u(uint32(p.a) == uint32(p.b)); got != want {
				t.Errorf("CmpL32Eq(%#x, %#x) = %d, want %d", p.a, p.b, got, want)
			}
		}
	})
	t.Run("CmpL32LessS", func(t *testing.T) {
		pairs := []struct{ a, b uint64 }{
			{0xF_FFFFFFFF, 0xF_00000001}, // int32 -1 < 1, but uint64 a > b
			{0x0_00000005, 0x0_00000003},
		}
		for _, p := range pairs {
			if got, want := CmpL32LessS(p.a, p.b), b2u(int32(p.a) < int32(p.b)); got != want {
				t.Errorf("CmpL32LessS(%#x, %#x) = %d, want %d", p.a, p.b, got, want)
			}
		}
	})
	t.Run("CmpL32LessU", func(t *testing.T) {
		pairs := []struct{ a, b uint64 }{
			{0x2_00000001, 0x1_00000002}, // uint32 1 < 2, but uint64 a > b
			{0x0_00000005, 0x0_00000003},
		}
		for _, p := range pairs {
			if got, want := CmpL32LessU(p.a, p.b), b2u(uint32(p.a) < uint32(p.b)); got != want {
				t.Errorf("CmpL32LessU(%#x, %#x) = %d, want %d", p.a, p.b, got, want)
			}
		}
	})
	t.Run("TestL32", func(t *testing.T) {
		pairs := []struct{ a, m uint64 }{
			{0x1_00000000, 0x1_00000000}, // low32 AND is 0, but 64-bit AND is not
			{0x0_00000006, 0x0_00000002},
		}
		for _, p := range pairs {
			if got, want := TestL32(p.a, p.m), b2u(uint32(p.a)&uint32(p.m) == 0); got != want {
				t.Errorf("TestL32(%#x, %#x) = %d, want %d", p.a, p.m, got, want)
			}
		}
	})
}

func TestLoadIdx(t *testing.T) {
	var p [8]uint64
	for i := range p {
		p[i] = uint64(i*i + 1)
	}
	for i := uint64(0); i < 8; i++ {
		if got := LoadIdx(&p, i); got != p[i] {
			t.Errorf("LoadIdx(p, %d) = %d, want %d", i, got, p[i])
		}
	}
}

func TestCopy16(t *testing.T) {
	var src, dst [16]byte
	for i := range src {
		src[i] = byte(i*7 + 1)
	}
	Copy16(&dst, &src)
	if dst != src {
		t.Errorf("Copy16: dst %v != src %v", dst, src)
	}
}
