// Code generated by command: go run asm.go -out lower_amd64.s -arm64 lower_arm64.s -stubs stub.go. DO NOT EDIT.

package arm64lower

func Add(x uint64, y uint64) uint64

func Sub(x uint64, y uint64) uint64

func Neg(x uint64) uint64

func AndOrXor(x uint64, y uint64) uint64

func ShlCL(x uint64, n uint64) uint64

func ShrCL(x uint64, n uint64) uint64

func RolCL(x uint64, n uint64) uint64

func ZeroExt32(x uint64) uint64

func HighByte(x uint64) uint64

func LoadIdx(p *[8]uint64, i uint64) uint64

func Copy16(dst *[16]byte, src *[16]byte)

func LessS(a uint64, b uint64) uint64

func GreaterEqS(a uint64, b uint64) uint64

func LessU(a uint64, b uint64) uint64

func AboveU(a uint64, b uint64) uint64

func Equal(a uint64, b uint64) uint64

func SelectEq(a uint64, b uint64, c uint64, d uint64) uint64

func SubGapEq(x uint64, y uint64) uint64

func DecGapZero(x uint64, y uint64) uint64

func CmpL32Eq(a uint64, b uint64) uint64

func CmpL32LessS(a uint64, b uint64) uint64

func CmpL32LessU(a uint64, b uint64) uint64

func TestL32(a uint64, m uint64) uint64

func CmpW16Eq(a uint64, b uint64) uint64

func CmpB8Ne(a uint64, b uint64) uint64

func TestW16Eq(a uint64, m uint64) uint64

func IMul2(x uint64, y uint64) uint64

func IMul3(x uint64) uint64

func MulWide(x uint64, y uint64) (lo uint64, hi uint64)

func IMulWide(x int64, y int64) (lo uint64, hi uint64)

func MulX(x uint64, y uint64) (lo uint64, hi uint64)

func ShlX(x uint64, n uint64) uint64

func ShrX(x uint64, n uint64) uint64

func SarX(x uint64, n uint64) uint64

func RorX(x uint64) uint64

func Bzhi(x uint64, n uint64) uint64

func Bextr88(x uint64) uint64

func Bextr4_12(x uint64) uint64

func SelLtS(a uint64, b uint64, c uint64, d uint64) uint64

func SelLeS(a uint64, b uint64, c uint64, d uint64) uint64

func SelGtS(a uint64, b uint64, c uint64, d uint64) uint64

func SelGeS(a uint64, b uint64, c uint64, d uint64) uint64

func SelLsU(a uint64, b uint64, c uint64, d uint64) uint64

func SelMi(a uint64, b uint64, c uint64, d uint64) uint64

func SelPl(a uint64, b uint64, c uint64, d uint64) uint64
