// Code generated by command: go run asm.go -out lower_amd64.s -arm64 lower_arm64.s -stubs stub.go. DO NOT EDIT.

package arm64lower

func Add(x uint64, y uint64) uint64

func Sub(x uint64, y uint64) uint64

func Neg(x uint64) uint64

func AndOrXor(x uint64, y uint64) uint64

func ShlCL(x uint64, n uint64) uint64

func ShrCL(x uint64, n uint64) uint64

func RolCL(x uint64, n uint64) uint64

func ZeroExt32(x uint64) uint64

func HighByte(x uint64) uint64

func LoadIdx(p *[8]uint64, i uint64) uint64

func Copy16(dst *[16]byte, src *[16]byte)

func LessS(a uint64, b uint64) uint64

func GreaterEqS(a uint64, b uint64) uint64

func LessU(a uint64, b uint64) uint64

func AboveU(a uint64, b uint64) uint64

func Equal(a uint64, b uint64) uint64

func SelectEq(a uint64, b uint64, c uint64, d uint64) uint64

func SubGapEq(x uint64, y uint64) uint64

func DecGapZero(x uint64, y uint64) uint64

func CmpL32Eq(a uint64, b uint64) uint64

func CmpL32LessS(a uint64, b uint64) uint64

func CmpL32LessU(a uint64, b uint64) uint64

func TestL32(a uint64, m uint64) uint64

func CmpW16Eq(a uint64, b uint64) uint64

func CmpB8Ne(a uint64, b uint64) uint64

func TestW16Eq(a uint64, m uint64) uint64

func IMul2(x uint64, y uint64) uint64

func IMul3(x uint64) uint64

func MulWide(x uint64, y uint64) (lo uint64, hi uint64)

func IMulWide(x int64, y int64) (lo uint64, hi uint64)

func MulX(x uint64, y uint64) (lo uint64, hi uint64)

func ShlX(x uint64, n uint64) uint64

func ShrX(x uint64, n uint64) uint64

func SarX(x uint64, n uint64) uint64

func RorX(x uint64) uint64

func Bzhi(x uint64, n uint64) uint64

func Bextr88(x uint64) uint64

func Bextr4_12(x uint64) uint64

func Bextr56_8(x uint64) uint64

func Bextr8_56(x uint64) uint64

func Bextr8_60(x uint64) uint64

func Bextr0_0(x uint64) uint64

func Bextr70_8(x uint64) uint64

func BzhiConst13(x uint64) uint64

func BzhiConst0(x uint64) uint64

func BzhiConst64(x uint64) uint64

func ShlXConst9(x uint64) uint64

func ShrXConst9(x uint64) uint64

func SetGe(a uint64, b uint64) uint64

func AdcAccum(x uint64, acc uint64) uint64

func BswapL(x uint64) uint64

func AddByte(x uint64, y uint64) uint64

func MovbHighDst(x uint64, y uint64) uint64

func MovbLowPreserve(x uint64, y uint64) uint64

func SelLtS(a uint64, b uint64, c uint64, d uint64) uint64

func SelLeS(a uint64, b uint64, c uint64, d uint64) uint64

func SelGtS(a uint64, b uint64, c uint64, d uint64) uint64

func SelGeS(a uint64, b uint64, c uint64, d uint64) uint64

func SelLsU(a uint64, b uint64, c uint64, d uint64) uint64

func SelMi(a uint64, b uint64, c uint64, d uint64) uint64

func SelPl(a uint64, b uint64, c uint64, d uint64) uint64

func SxL(x uint64) uint64

func SxB(x uint64) uint64

func SxBL(x uint64) uint64

func SxWL(x uint64) uint64

func NegL(x uint64) uint64

func NotL(x uint64) uint64

func NotQ(x uint64) uint64

func RolL7(x uint64) uint64

func RorQ9(x uint64) uint64

func RorL9(x uint64) uint64

func BtrQ5(x uint64) uint64

func BtcQ5(x uint64) uint64

func PopcntQ(x uint64) uint64

func SarQ3(x uint64) uint64

func SarL3(x uint64) uint64

func IncL(x uint64) uint64

func ShlB2(x uint64) uint64

func BsfQ(x uint64) uint64

func TzcntQ(x uint64) uint64

func AddL(x uint64, y uint64) uint64

func SubL(x uint64, y uint64) uint64

func AndL(x uint64, y uint64) uint64

func OrL(x uint64, y uint64) uint64

func ImulL(x uint64, y uint64) uint64

func XchgQ(x uint64, y uint64) uint64

func LeaL(x uint64, y uint64) uint64

func VecZero(dst *[16]byte)

func VecCopyIdx(dst *[32]byte, src *[32]byte, i uint64)

func VecCopy(dst *[32]byte, src *[32]byte)

func Prop0(x uint64, y uint64) uint64

func Prop1(x uint64, y uint64) uint64

func Prop2(x uint64, y uint64) uint64

func Prop3(x uint64, y uint64) uint64

func Prop4(x uint64, y uint64) uint64

func Prop5(x uint64, y uint64) uint64

func Prop6(x uint64, y uint64) uint64

func Prop7(x uint64, y uint64) uint64

func Prop8(x uint64, y uint64) uint64

func Prop9(x uint64, y uint64) uint64

func Prop10(x uint64, y uint64) uint64

func Prop11(x uint64, y uint64) uint64

func Prop12(x uint64, y uint64) uint64

func Prop13(x uint64, y uint64) uint64

func Prop14(x uint64, y uint64) uint64

func Prop15(x uint64, y uint64) uint64

func Prop16(x uint64, y uint64) uint64

func Prop17(x uint64, y uint64) uint64

func Prop18(x uint64, y uint64) uint64

func Prop19(x uint64, y uint64) uint64

func Prop20(x uint64, y uint64) uint64

func Prop21(x uint64, y uint64) uint64

func Prop22(x uint64, y uint64) uint64

func Prop23(x uint64, y uint64) uint64

func Prop24(x uint64, y uint64) uint64

func Prop25(x uint64, y uint64) uint64

func Prop26(x uint64, y uint64) uint64

func Prop27(x uint64, y uint64) uint64

func Prop28(x uint64, y uint64) uint64

func Prop29(x uint64, y uint64) uint64

func Prop30(x uint64, y uint64) uint64

func Prop31(x uint64, y uint64) uint64

func Prop32(x uint64, y uint64) uint64

func Prop33(x uint64, y uint64) uint64

func Prop34(x uint64, y uint64) uint64

func Prop35(x uint64, y uint64) uint64

func Prop36(x uint64, y uint64) uint64

func Prop37(x uint64, y uint64) uint64

func Prop38(x uint64, y uint64) uint64

func Prop39(x uint64, y uint64) uint64

func Prop40(x uint64, y uint64) uint64

func Prop41(x uint64, y uint64) uint64

func Prop42(x uint64, y uint64) uint64

func Prop43(x uint64, y uint64) uint64

func Prop44(x uint64, y uint64) uint64

func Prop45(x uint64, y uint64) uint64

func Prop46(x uint64, y uint64) uint64

func Prop47(x uint64, y uint64) uint64

func Prop48(x uint64, y uint64) uint64

func Prop49(x uint64, y uint64) uint64

func Prop50(x uint64, y uint64) uint64

func Prop51(x uint64, y uint64) uint64

func Prop52(x uint64, y uint64) uint64

func Prop53(x uint64, y uint64) uint64

func Prop54(x uint64, y uint64) uint64

func Prop55(x uint64, y uint64) uint64

func Prop56(x uint64, y uint64) uint64

func Prop57(x uint64, y uint64) uint64

func Prop58(x uint64, y uint64) uint64

func Prop59(x uint64, y uint64) uint64

func Prop60(x uint64, y uint64) uint64

func Prop61(x uint64, y uint64) uint64

func Prop62(x uint64, y uint64) uint64

func Prop63(x uint64, y uint64) uint64

func MemProp0(x uint64, y uint64, p *[8]uint64) uint64

func MemProp1(x uint64, y uint64, p *[8]uint64) uint64

func MemProp2(x uint64, y uint64, p *[8]uint64) uint64

func MemProp3(x uint64, y uint64, p *[8]uint64) uint64

func MemProp4(x uint64, y uint64, p *[8]uint64) uint64

func MemProp5(x uint64, y uint64, p *[8]uint64) uint64

func MemProp6(x uint64, y uint64, p *[8]uint64) uint64

func MemProp7(x uint64, y uint64, p *[8]uint64) uint64

func MemProp8(x uint64, y uint64, p *[8]uint64) uint64

func MemProp9(x uint64, y uint64, p *[8]uint64) uint64

func MemProp10(x uint64, y uint64, p *[8]uint64) uint64

func MemProp11(x uint64, y uint64, p *[8]uint64) uint64

func MemProp12(x uint64, y uint64, p *[8]uint64) uint64

func MemProp13(x uint64, y uint64, p *[8]uint64) uint64

func MemProp14(x uint64, y uint64, p *[8]uint64) uint64

func MemProp15(x uint64, y uint64, p *[8]uint64) uint64

func MemProp16(x uint64, y uint64, p *[8]uint64) uint64

func MemProp17(x uint64, y uint64, p *[8]uint64) uint64

func MemProp18(x uint64, y uint64, p *[8]uint64) uint64

func MemProp19(x uint64, y uint64, p *[8]uint64) uint64

func MemProp20(x uint64, y uint64, p *[8]uint64) uint64

func MemProp21(x uint64, y uint64, p *[8]uint64) uint64

func MemProp22(x uint64, y uint64, p *[8]uint64) uint64

func MemProp23(x uint64, y uint64, p *[8]uint64) uint64

func MemProp24(x uint64, y uint64, p *[8]uint64) uint64

func MemProp25(x uint64, y uint64, p *[8]uint64) uint64

func MemProp26(x uint64, y uint64, p *[8]uint64) uint64

func MemProp27(x uint64, y uint64, p *[8]uint64) uint64

func MemProp28(x uint64, y uint64, p *[8]uint64) uint64

func MemProp29(x uint64, y uint64, p *[8]uint64) uint64

func MemProp30(x uint64, y uint64, p *[8]uint64) uint64

func MemProp31(x uint64, y uint64, p *[8]uint64) uint64

func MovbzxHigh(x uint64) uint64

func CmovL32(x uint64, y uint64) uint64

func BextrMem(p *[4]uint64, i uint64, ctrl uint64) uint64

func XorSelfEq(x uint64) uint64

func MovLNegImm() uint64

func IncLMem(p *[2]uint32)

func DecLMem(p *[2]uint32)

func IncQMem(p *[2]uint64)

func CmpBHigh(x uint64) uint64

func MovWLoad(x uint64, p *uint16) uint64

func MulXAlias(x uint64, y uint64) uint64

func TestQImm(x uint64, y uint64) uint64

func FlagsAcrossTransparent(a uint64, b uint64) uint64

func XorlSign(x uint64, y uint64) uint64

func XorlMem(p *[2]uint32, v uint64)

func BzhiConst256(x uint64) uint64

func BzhiConstNeg(x uint64) uint64

func IncQ(x uint64) uint64

func DecL(x uint64) uint64

func ShrL5(x uint64) uint64

func SxWQ(x uint64) uint64

func BsrQ(x uint64) uint64

func BtsQ5(x uint64) uint64

func ZxLQ(p *uint64) uint64

func MovW(x uint64, y uint64) uint64

func LeaQ(x uint64, y uint64) uint64

func TestQZero(x uint64, y uint64) uint64

func TestBZero(x uint64, y uint64) uint64

func VecCopyReg(dst *[16]byte, src *[16]byte)

func SetAll(a uint64, b uint64) uint64

func JmpAll(a uint64, b uint64) uint64

func CmovAll(a uint64, b uint64) uint64
